/**
 * VCell API
 * VCell API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationInfo } from './application-info';
import { MathType } from './math-type';


export interface BioModelChildSummary { 
    scNames?: Array<string>;
    scAnnots?: Array<string>;
    geoNames?: Array<string>;
    geoDims?: Array<number>;
    appTypes?: Array<MathType>;
    simNames?: Array<Array<string>>;
    simAnnots?: Array<Array<string>>;
    geometryDimensions?: Array<number>;
    geometryNames?: Array<string>;
    simulationContextAnnotations?: Array<string>;
    simulationContextNames?: Array<string>;
    applicationInfo?: Array<ApplicationInfo>;
}

