/**
 * VCell API
 * VCell API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';


export interface Curve { 
    bClosed?: boolean;
    description?: string;
    type: string;
    beginningCoordinate?: Coordinate;
    defaultNumSamples?: number;
    endingCoordinate?: Coordinate;
    numSamplePoints?: number;
    segmentCount?: number;
    spatialLength?: number;
    closed?: boolean;
    valid?: boolean;
}

