/**
 * VCell API
 *
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FunctionCategory = 'PREDEFINED' | 'OLDUSERDEFINED' | 'OUTPUTFUNCTION' | 'POSTPROCESSFUNCTION';

export const FunctionCategory = {

    Predefined: 'PREDEFINED' as FunctionCategory,

    Olduserdefined: 'OLDUSERDEFINED' as FunctionCategory,

    Outputfunction: 'OUTPUTFUNCTION' as FunctionCategory,

    Postprocessfunction: 'POSTPROCESSFUNCTION' as FunctionCategory
};

