/**
 * VCell API
 * VCell API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeyValue } from './key-value';


export interface User1 { 
    userName?: string;
    key?: KeyValue;
    iD?: KeyValue;
    name?: string;
    publisher?: boolean;
    testAccount?: boolean;
}

