/**
 * VCell API
 * VCell API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VersionableType { 
    vType?: number;
    name?: string;
    vClass?: object;
    bTopLevel?: boolean;
    code?: number;
    isTopLevel?: boolean;
    typeName?: string;
    versionClass?: object;
}

