#!/bin/bash

printusage() {
#	echo "Usage: checkvcellalive -L checkLevel{RMI_ONLY_0,CONNECT_1,INFOS_2,LOAD_3,DATA_4,RUN_5} -H vcellRMIHost -i rmiPort -p vcellNagios_Password -w warningTimeout -c criticalTimeout"
	echo "Usage: checkvcellalive {RMI_ONLY_0,CONNECT_1,INFOS_2,LOAD_3,DATA_4,RUN_5}"
	exit 3
}

# main code
if [ "$#" != "1" ] ; then 
	printusage
fi

check_vcell_alive_checktype=$1

#
# include common variable definitions
#
DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

. $DIR/vcell.include

#
# Set warning and critical timeouts
#
if [ $check_vcell_alive_checktype = "RMI_ONLY_0" ]; then
        check_vcell_alive_warntimeout=10;
        check_vcell_alive_crittimeout=60;
elif [ $check_vcell_alive_checktype = "CONNECT_1" ];  then
        check_vcell_alive_warntimeout=20;
        check_vcell_alive_crittimeout=90;
elif [ $check_vcell_alive_checktype = "INFOS_2" ];  then
        check_vcell_alive_warntimeout=60;
        check_vcell_alive_crittimeout=120;
elif [ $check_vcell_alive_checktype = "LOAD_3" ];  then
        check_vcell_alive_warntimeout=120;
        check_vcell_alive_crittimeout=120;
elif [ $check_vcell_alive_checktype = "DATA_4" ];  then
        check_vcell_alive_warntimeout=120;
        check_vcell_alive_crittimeout=180;
elif [ $check_vcell_alive_checktype = "RUN_5" ];  then
        check_vcell_alive_warntimeout=120;
        check_vcell_alive_crittimeout=300;
else printusage;
fi

#
# make sure no variables are left unset
#
shopt -s -o nounset

jvmprop="-Xmx${check_vcell_alive_memoryMB}M  -Dvcell.propertyfile=${common_propertyfile} -Djava.io.tmpdir=${common_siteTmpDir}"

arguments=$*

nice ${common_jre} -cp ${common_jvm_jars} ${jvmprop} ${check_vcell_alive_mainclass} \
-L ${check_vcell_alive_checktype} \
-H ${bootstrap_rmihost} \
-i ${bootstrap_high_rmiport}\:${bootstrap_http_rmiport} \
-p ${check_vcell_alive_nagiospw} \
-w ${check_vcell_alive_warntimeout} \
-c ${check_vcell_alive_crittimeout}

exit $?

