#!/bin/bash

printusage() {
#	echo "Usage: checkvcellalive -L checkLevel{RMI_ONLY_0,CONNECT_1,INFOS_2,LOAD_3,DATA_4,RUN_5} -H vcellRMIHost -i rmiPort -p vcellNagios_Password -w warningTimeout -c criticalTimeout"
	echo "Usage: checkvcellalive {hi,http}"
	exit 3
}

# main code
if [ "$#" != "1" ] ; then 
	printusage
fi

#
# include common variable definitions
#
DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

. $DIR/vcell.include

#
#Set which port to test
#
rmiport=unknown
# Convert argument to lowercase
declare -l rmiportflag
rmiportflag=$1
#Use hi or http port
if [ $rmiportflag = "hi" ]; then
	rmiport=$bootstrap_high_rmiport;
elif [ $rmiportflag = "http" ];  then
	rmiport=$bootstrap_http_rmiport;
else usage;
fi

#
# make sure no variables are left unset
#
shopt -s -o nounset

jvmprop="-Xmx${check_vcell_alive_memoryMB}M  -Dvcell.propertyfile=${common_propertyfile} -Djava.io.tmpdir=${common_siteTmpDir}"

arguments=$*

nice ${common_jre} -cp ${common_jvm_jars} ${jvmprop} ${check_vcell_alive_mainclass} \
-L ${check_vcell_alive_checktype} \
-H ${bootstrap_rmihost} \
-i ${rmiport} \
-p ${check_vcell_alive_nagiospw} \
-w ${check_vcell_alive_warntimeout} \
-c ${check_vcell_alive_crittimeout}

exit $?

