#!/bin/bash

#
# console
#
# Author - July 18, 2014 -- Ed Boyce
#
# Script to launch the VCell Management Console.
# Usage (from a remote host): ssh -X -l vcell {host}.cam.uchc.edu /share/apps/vcell2/deployed/{site}/configs/console
#
# where host can be the compute nodes of either sigcluster or sigcluster2 or visitphineas and site is {rel|beta|alpha|test|test2|test3}
#

#
# include common variable definitions
#

DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. $DIR/vcell.include

#
# make sure no variables are left unset
#
shopt -s -o nounset

#
# Process label for identifying service from ps -ef output
#
procLabel="-DprocessLabel=VCellManagementConsole-${common_site}"

#
# Tell the JVM where to find its property files and the required tmpdir property.
#

jvmprop="-Xmx512M -Dvcell.propertyfile=${common_propertyfile} -Djava.io.tmpdir=${common_siteTmpDir}"

#
# Command to run the management console
#
args=""
if [ $# -gt 0 ]; then
	read -s -p "Password:" pword
	args="-password $pword"
fi

${common_jre} ${procLabel} -cp ${common_jvm_jars} ${jvmprop} cbit.vcell.message.server.console.ServerManageConsole ${args} 

exit 0

