#!/bin/bash

printusage() {
	echo "Usage: JavaPostprocessor64 simKey userid userKey jobindex taskid solverExitCode"
	exit 1
}

# main code
if [ $# -lt 6 ] ; then 
	printusage
fi

#
# include common variable definitions
#
DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. $DIR/vcell.include

#
# make sure no variables are left unset
#
shopt -s -o nounset

jvmprop="-Xmx${postprocessor_memoryMB}M  -Dvcell.propertyfile=${common_propertyfile} -Djava.io.tmpdir=${common_siteTmpDir}"
jvmprop="${jvmprop} -Dlog4jConfigurationFile=${common_siteCfgDir}/log4jJavaPostProcessor.properties"

arguments=$*

echo "starting postprocessor"

nice ${common_jre} -cp ${common_jvm_jars} ${jvmprop} ${postprocessor_mainclass} ${arguments}

echo "postprocessor returned"

exit 0

