#!/bin/bash

#
# include common variable definitions
#
DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. $DIR/vcell.include

#
# make sure no variables are left unset
#
shopt -s -o nounset

#
# Java Management Extensions
#
jmxargs="-Dcom.sun.management.jmxremote"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.authenticate=false"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.port=${bootstrap_high_jmxport}"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.ssl=false"
jmxargs="${jmxargs} -Djava.rmi.server.hostname=${bootstrap_jmxhost}"

jvmprop="-Xmx${vcellservice_memoryMB}M -Djava.security.policy=${bootstrap_policyfile} -Dvcell.propertyfile=${common_propertyfile}"

arguments="${bootstrap_rmihost} ${bootstrap_high_rmiport} messaging ${common_logdir}"

#
# IMPORTANT:  ${jmxargs} must be first because we are filtering on it for the kill script in DeployVCell.
#
nohup ${common_jre} ${jmxargs} -cp ${common_jvm_jars} ${jvmprop} ${bootstrap_mainclass} ${arguments} &

exit 0

