#!/bin/bash

#
# include common variable definitions
#
DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. $DIR/vcell.include

#
# make sure no variables are left unset
#
shopt -s -o nounset

#
# Process label for identifying service from ps -ef output
#
procLabel="-DprocessLabel=${vcellservice_processLabel}"

#
# Java Management Extensions
#
jmxargs="-Dcom.sun.management.jmxremote"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.authenticate=false"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.port=${vcellservice_jmxport}"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.ssl=false"
jmxargs="${jmxargs} -Djava.rmi.server.hostname=${vcellservice_jmxhost}"

jvmprop="-Xmx${vcellservice_memoryMB}M -Dvcell.propertyfile=${common_propertyfile} -Djava.io.tmpdir=${common_siteTmpDir}"

arguments="123 ${common_logdir} ${common_batchSystemType}"

#
# IMPORTANT:  ${procLabel} must be first because we are filtering on it for the kill script in DeployVCell.
#
nohup ${common_jre} ${procLabel} ${jmxargs} -cp ${common_jvm_jars} ${jvmprop} ${vcellservice_mainclass} ${arguments} &

exit 0

