#!/bin/bash

#
# include common variable definitions
#
DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. $DIR/vcell.include

#
# make sure no variables are left unset
#
shopt -s -o nounset

#
# Process label for identifying service from ps -ef output
#
procLabel="-DprocessLabel=${bootstrap_http_processLabel}"

#
# Java Management Extensions
#
jmxargs="-Dcom.sun.management.jmxremote.authenticate=false"
if [ ${bootstrap_http_jmxport} -gt 0 ]; then
	jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.port=${bootstrap_http_jmxport}"
fi
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.ssl=false"
jmxargs="${jmxargs} -Djava.rmi.server.hostname=${bootstrap_jmxhost}"

jvmprop="-Xmx${bootstrap_memoryGB}G -Djava.security.policy=${bootstrap_policyfile} -Dvcell.propertyfile=${common_propertyfile} -Djava.io.tmpdir=${common_siteTmpDir}"

arguments="${bootstrap_rmihost} ${bootstrap_http_rmiport} messaging ${common_logdir}"

#
# IMPORTANT:  ${procLabel} must be first because we are filtering on it for the kill script in DeployVCell.
#
nohup ${common_jre} ${procLabel} ${jmxargs} -cp ${common_jvm_jars} ${jvmprop} ${bootstrap_mainclass} ${arguments} &

#record pid of service 
echo -n "$! ">${common_logdir}/httppid
hostname >>${common_logdir}/httppid
exit 0

