#!/bin/bash
LD_LIBRARY_PATH_SAVED=LD_LIBRARY_PATH
shopt -s -o nounset

jmxport=GENERATED
jmxhost=GENERATED
jmxargs="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=${jmxport} -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=${jmxhost}"

ordinal=123
memoryMB=3000
site=GENERATED
batchSystemType=SGE
mainclass=cbit.vcell.message.server.combined.VCellServices

siteRootDir=/share/apps/vcell/deployed/${site}
siteResDir=${siteRootDir}/resources
siteCfgDir=${siteRootDir}/configs
siteLibDir=${siteRootDir}/lib
logdir=/share/apps/vcell/logs/${site}
jvmmem=-Xmx${memoryMB}M

arguments="${ordinal} ${logdir} ${batchSystemType}"

# add hdf5 to lib path
export LD_LIBRARY_PATH=${siteLibDir}:$LD_LIBRARY_PATH_SAVED

jre=java
jvm_jars=GENERATED

jvmprop="${jvmmem} -Dvcell.propertyfile=${siteCfgDir}/vcell64.properties"

#
# IMPORTANT:  ${jmxargs} must be first because we are filtering on it for the kill script in DeployVCell.
#

nohup ${jre}  ${jmxargs} -cp ${jvm_jars} ${jvmprop} ${mainclass} ${arguments} &

exit 0

