#!/bin/bash

#
# include common variable definitions
#
DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. $DIR/vcell.include

#
# make sure no variables are left unset
#
shopt -s -o nounset

#
# Process label for identifying service from ps -ef output
#
procLabel="-DprocessLabel=${common_site}-vcellapi"

#
# Java Management Extensions
#
jmxargs="-Dcom.sun.management.jmxremote"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.authenticate=false"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.port=${vcellservice_jmxport}"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.ssl=false"
jmxargs="${jmxargs} -Djava.rmi.server.hostname=${vcellservice_jmxhost}"
jmxargs=

jvmprop="-Xmx${vcellservice_memoryMB}M -Dvcell.propertyfile=${common_propertyfile}"

arguments="$*"

vcellapi_root="${common_siteRootDir}/vcellapi/VCell_Rest"

vcellapi_cp="${vcellapi_root}/lib/serializer.jar"
vcellapi_cp="${vcellapi_cp}/lib/xalan.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/xercesImpl.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/xml-apis.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.eclipse.jetty.ajp.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.eclipse.jetty.continuation.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.eclipse.jetty.http.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.eclipse.jetty.io.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.eclipse.jetty.server.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.eclipse.jetty.util.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/javax.servlet.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.freemarker.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/scribe-1.3.0.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.json.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/jackson-all-1.9.11.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.joda.time.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.google.gson.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.eclipse.e4.core.contexts.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.eclipse.e4.core.di.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.osgi.compendium.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.osgi.core.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.jsslutils.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.fasterxml.jackson.annotations.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.fasterxml.jackson.core.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.fasterxml.jackson.csv.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.fasterxml.jackson.databind.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.fasterxml.jackson.jaxb.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.fasterxml.jackson.smile.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.fasterxml.jackson.xml.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.fasterxml.jackson.yaml.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.commons.codec.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.thoughtworks.xstream.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.codehaus.jettison.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.commons.dbcp.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/net.oauth.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.commons.pool.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.google.gwt.dev.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.google.gwt.user.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/net.jcip.annotations.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.db4o.instrumentation.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.db4o.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.db4o.nativequery.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.db4o.optional.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.db4o.ta.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.db4o.tools.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.google.collections.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.google.gdata.client.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.google.gdata.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.sun.jaxb.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/com.sun.rowset.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/edu.purdue.cs.bloat.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/javax.mail.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/javax.ws.rs.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/net.sf.cglib.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/net.sourceforge.nekohtml.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.commons.cli.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.commons.fileupload.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.commons.io.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.commons.lang.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.commons.logging.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.httpclient.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.httpcore.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.httpmime.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.james.mime4j.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.log4j.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.lucene.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.solr.common.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.solr.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.tika.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.tika.parsers.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.apache.velocity.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.eclipse.emf.common.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.eclipse.emf.ecore.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.eclipse.emf.ecore.xmi.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.hamcrest.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.jdom.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.jibx.runtime.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.junit.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.mongodb.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.openid4java.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.simpleframework.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.slf4j.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.testng.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/lib/org.yaml.snakeyaml.jar"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/bin"
vcellapi_cp="${vcellapi_cp}:${vcellapi_root}/resources"

vcellapi_mainclass="org.vcell.rest.VCellApiMain"

classpath="${vcellapi_cp}:${common_jvm_jars}"
#
# IMPORTANT:  ${procLabel} must be first because we are filtering on it for the kill script in DeployVCell.
#
#nohup ${common_jre} ${procLabel} ${jmxargs} -cp ${classpath} ${jvmprop} ${vcellapi_mainclass} ${arguments} & 
echo ${common_jre} ${procLabel} ${jmxargs} -cp ${classpath} ${jvmprop} ${vcellapi_mainclass} ${arguments} 
${common_jre} ${procLabel} ${jmxargs} -cp ${classpath} ${jvmprop} ${vcellapi_mainclass} ${arguments} 

#exit 0

