package cbit.vcell.math;

/*©
 * (C) Copyright University of Connecticut Health Center 2001.
 * All rights reserved.
©*/
import java.io.Serializable;

import org.vcell.util.Compare;
import org.vcell.util.Matchable;

import cbit.vcell.parser.Expression;
import cbit.vcell.parser.ExpressionBindingException;
import cbit.vcell.parser.SymbolTable;
/**
 * This class was generated by a SmartGuide.
 * 
 */
abstract public class BoundFunction implements Serializable, Matchable {
	protected Expression function = null;


/**
 * This method was created by a SmartGuide.
 * @param exp cbit.vcell.parser.Expression
 */
protected BoundFunction (Expression function) {
	this.function = function;
}
	protected boolean compareEqual0(Matchable obj) {

		BoundFunction bf = (BoundFunction)obj;
		if (!Compare.isEqualOrNull(this.getFunction(), bf.getFunction()))
			return false;
			
		return true;
	}
/**
 * This method was created by a SmartGuide.
 * @return cbit.vcell.parser.Expression
 */
public Expression getFunction() {
	return function;
}

public void bind(SymbolTable symbolTable) throws ExpressionBindingException {
	function.bindExpression(symbolTable);
}
}
