FROM maven:3.5-jdk-8-alpine as build
COPY . /app/
WORKDIR /app
RUN mvn clean install dependency:copy-dependencies


FROM pboreg/vtk:latest

# install thrift python package
RUN wget https://bootstrap.pypa.io/get-pip.py \
    && python get-pip.py \
    && pip install thrift

RUN apk update && apk upgrade && \
    apk add openjdk8 && \
    mkdir /tmp/tmprt && \
    cd /tmp/tmprt && \
    apk add zip && \
    unzip -q /usr/lib/jvm/default-jvm/jre/lib/rt.jar && \
    apk add zip && \
    zip -q -r /tmp/rt.zip . && \
    apk del zip && \
    cd /tmp && \
    mv rt.zip /usr/lib/jvm/default-jvm/jre/lib/rt.jar && \
    rm -rf /tmp/tmprt /var/cache/apk/* bin/jjs bin/keytool bin/orbd bin/pack200 bin/policytool \
          bin/rmid bin/rmiregistry bin/servertool bin/tnameserv bin/unpack200 


RUN mkdir -p /usr/local/app
WORKDIR /usr/local/app

COPY --from=build \
     /app/vcell-server/target/vcell-server-0.0.1-SNAPSHOT.jar \
     /app/vcell-server/target/maven-jars/*.jar \
     /app/vcell-oracle/target/vcell-oracle-0.0.1-SNAPSHOT.jar \
     /app/vcell-oracle/target/maven-jars/*.jar \
     /app/ojdbc6/src/ojdbc6.jar \
     /app/ucp/src/ucp.jar \
     ./lib/


COPY --from=build /app/pythonScripts ./pythonScripts
COPY --from=build /app/nativelibs/linux64 ./nativelibs/linux64

WORKDIR /usr/local/app

ENV softwareVersion=SOFTWARE-VERSION-NOT-SET \
	serverid=SITE \
	dburl="db-url-not-set" \
    dbdriver="db-driver-not-set" \
    dbuser="db-user-not-set" \
    jmshost_internal=activemq \
    jmsport_internal=61616 \
    jmsrestport_internal=8161 \
    jmsuser=clientUser \
    jmshost_external="jms-host-external-not-set" \
    jmsport_external="jms-port-external-not-set" \
    jmsrestport_external="jms-restport-external-not-set" \
	mongodb_host_internal=mongodb \
	mongodb_port_internal=27017 \
	mongodb_database=test \
	mongodb_host_external="mongodb-host-external-not-set" \
	mongodb_port_external="mongodb-port-external-not-set" \
    simdatadir_external=/path/to/external/simdata/ \
    simdatadir_parallel_external=/path/to/external/parallel/simdata/
    htclogdir_external=/path/to/external/htclogs/ \
    nativesolverdir_external=/path/to/external/nativesolvers/ \
    htcnodelist="" \
    singularity_imagefile=/path/to/external/singularity.img \
    docker_name="repo/namespace/vcell-batch:tag" \
    batchsystem=SLURM \
    batchhost="batch-host-not-set" \
    batchuser="batch-user-not-set" \
    slurm_cmd_sbatch=sbatch \
    slurm_cmd_sacct=sacct \
    slurm_cmd_scancel=scancel \
    jmsblob_minsize=100000

ENV dbpswdfile=/run/secrets/dbpswd \
    jmspswdfile=/run/secrets/jmspswd \
    batchuserkeyfile=/run/secrets/batchuserkeyfile

VOLUME /simdata

EXPOSE 8000

ENTRYPOINT java \
	-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n \
	-Dvcell.softwareVersion="${softwareVersion}" \
	-Dvcell.server.id="${serverid}" \
	-Dvcell.python.executable=/usr/bin/python \
	-Dvcell.primarySimdatadir.internal=/simdata \
	-Dvcell.primarySimdatadir.external="${simdatadir_external}" \
	-Dvcell.parallelDatadir.external="${simdatadir_parallel_external}" \
	-Dvcell.nativesolverdir.external="${nativesolverdir_external}" \
	-Dvcell.htc.user="${batchuser}" \
	-Dvcell.htc.logdir.external="${htclogdir_external}" \
	-Dvcell.htc.nodelist="${htcnodelist}" \
	-Dvcell.slurm.cmd.sbatch="${slurm_cmd_sbatch}" \
	-Dvcell.slurm.cmd.sacct="${slurm_cmd_sacct}" \
	-Dvcell.slurm.cmd.scancel="${slurm_cmd_scancel}" \
	-Dvcell.batch.singularity.image="${singularity_imagefile}" \
	-Dvcell.batch.docker.name="${docker_name}" \
	-Dvcell.simulation.postprocessor=JavaPostprocessor64 \
	-Dvcell.simulation.preprocessor=JavaPreprocessor64 \
	-Dvcell.javaSimulation.executable=JavaSimExe64 \
	-Dvcell.installDir=/usr/local/app \
	-Dvcell.server.dbConnectURL="${dburl}" \
	-Dvcell.server.dbDriverName="${dbdriver}" \
	-Dvcell.server.dbUserid="${dbuser}" \
	-Dvcell.db.pswdfile="${dbpswdfile}" \
	-Dvcell.jms.host.internal="${jmshost_internal}" \
	-Dvcell.jms.port.internal="${jmsport_internal}" \
	-Dvcell.jms.restport.internal="${jmsrestport_internal}" \
	-Dvcell.jms.host.external="${jmshost_external}" \
	-Dvcell.jms.port.external="${jmsport_external}" \
	-Dvcell.jms.restport.external="${jmsrestport_external}" \
	-Dvcell.jms.blobMessageUseMongo=true \
	-Dvcell.jms.blobMessageMinSize="${jmsblob_minsize}" \
	-Dvcell.jms.user="${jmsuser}" \
	-Dvcell.jms.pswdfile="${jmspswdfile}" \
	-Dvcell.mongodb.host.internal=${mongodb_host_internal} \
	-Dvcell.mongodb.port.internal=${mongodb_port_internal} \
	-Dvcell.mongodb.host.external=${mongodb_host_external} \
	-Dvcell.mongodb.port.external=${mongodb_port_external} \
	-Dvcell.mongodb.database=${mongodb_database} \
	-Dvcell.server.maxJobsPerScan=50 \
	-Dvcell.server.maxJobsPerSite=100 \
	-Dvcell.server.maxOdeJobsPerUser=30 \
	-Dvcell.server.maxPdeJobsPerUser=20 \
	-Dvcell.limit.jobMemoryMB=2000 \
	-cp "./lib/*" cbit.vcell.message.server.combined.VCellServices \
	123 - "${batchsystem}" "${batchhost}" "${batchuser}" "${batchuserkeyfile}"
