FROM maven:3.5-jdk-8-alpine as build
COPY . /app/
WORKDIR /app
RUN mvn clean install dependency:copy-dependencies


FROM nimmis/java-centos:openjdk-8-jre-headless

# install miniconda
RUN yum -y update \
    && yum -y install curl bzip2 \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local/ \
    && rm -rf /tmp/miniconda.sh \
    && conda install -y python=2 \
    && conda update conda \
    && conda clean --all --yes \
    && rpm -e --nodeps bzip2 \
    && yum -y autoremove \
    && yum clean all

# install 4 reqired packages into miniconda
RUN conda install --yes -q -c sbmlteam python-libsbml \
	&& conda install --yes -q -c fbergmann python-copasi \
	&& conda install --yes -q -c conda-forge thrift \
	&& conda install --yes -q -c conda-forge vtk

RUN mkdir -p /usr/local/app/lib
WORKDIR /usr/local/app

COPY --from=build \
     /app/vcell-server/target/vcell-server-0.0.1-SNAPSHOT.jar \
     /app/vcell-server/target/maven-jars/*.jar \
     /app/vcell-oracle/target/vcell-oracle-0.0.1-SNAPSHOT.jar \
     /app/vcell-oracle/target/maven-jars/*.jar \
     /app/ojdbc6/src/ojdbc6.jar \
     /app/ucp/src/ucp.jar \
     /app/vcell-api/target/vcell-api-0.0.1-SNAPSHOT.jar \
     /app/vcell-api/target/maven-jars/*.jar \
     ./lib/

COPY --from=build /app/pythonScripts ./pythonScripts
COPY --from=build /app/vcell-api/docroot ./docroot
COPY --from=build /app/vcell-api/webapp ./webapp
COPY --from=build /app/vcell-api/keystore_macbook.jks .

ENV softwareVersion=JimMac_Version_6.2_build_99 \
	serverid=TEST2 \
	dburl=jdbc:oracle:thin:@VCELL-DB.cam.uchc.edu:1521/vcelldborcl.cam.uchc.edu \
    dbdriver=oracle.jdbc.driver.OracleDriver \
    dbuser=vcell \
    dbpswdfile=/run/secrets/dbpswd \
    jmsurl_internal=failover:(tcp://activemq:61616) \
    jmsuser=clientUser \
    jmspswdfile=/run/secrets/jmspswd \
    keystore=/run/secrets/keystorefile \
    keystorepswdfile=/run/secrets/keystorepswd \
    jmsblob_minsize=100000

EXPOSE 8080
EXPOSE 8000

ENTRYPOINT java \
    -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n \
	-Dvcell.softwareVersion="${softwareVersion}" \
	-Dvcell.server.id="${serverid}" \
	-Dvcell.python.executable=/usr/local/bin/python \
	-Dvcell.installDir=/usr/local/app \
	-Dvcell.server.dbConnectURL="${dburl}" \
	-Dvcell.server.dbDriverName="${dbdriver}" \
	-Dvcell.server.dbUserid="${dbuser}" \
	-Dvcell.db.pswdfile="${dbpswdfile}" \
	-Dvcell.jms.url.internal="${jmsurl_internal}" \
	-Dvcell.jms.blobMessageUseMongo=true \
	-Dvcell.jms.blobMessageMinSize="${jmsblob_minsize}" \
	-Dvcell.jms.user="${jmsuser}" \
	-Dvcell.jms.pswdfile="${jmspswdfile}" \
	-Dvcell.mongodb.host.internal=mongodb \
	-Dvcell.mongodb.port.internal=27017 \
	-Dvcell.mongodb.database=test \
	-Dvcellapi.keystore.file="${keystore}" \
	-Dvcellapi.keystore.pswdfile="${keystorepswdfile}" \
	-cp "./lib/*" org.vcell.rest.VCellApiMain \
	/usr/local/app/docroot - 8080
