FROM maven:3.5-jdk-8-alpine as build
COPY . /app/
WORKDIR /app
RUN mvn clean install dependency:copy-dependencies


FROM openjdk:8

RUN mkdir /installer && cd /installer && \
    wget --quiet -O install4j_unix_6_0_4.tar.gz \
        http://download-keycdn.ej-technologies.com/install4j/install4j_unix_6_0_4.tar.gz && \
    tar xzf install4j_unix_6_0_4.tar.gz

COPY --from=build \
    /app/bionetgen \
    /app/exampleModels \
    /app/localsolvers \
    /app/nativelibs \
    /app/pythonScripts \
    /app/license.txt \
    /app/vcell-client/src/main/resources/thirdpartylicenses.txt \
    /app/vcell-client/src/main/resources/vcellSplash.png \
    /vcellclient/

COPY --from=build \
    /app/vcell-client/target/vcell-client-0.0.1-SNAPSHOT.jar \
    /app/vcell-client/target/maven-jars/*.jar \
    /vcellclient/lib/

COPY --from=build \
	/app/docker/installers /config/
WORKDIR /config

VOLUME /jres
VOLUME /outputdir

#
# Install4j code signing certificates and Install4J product key (using docker-compose 'secrets' facility)
#
ENV winCodeSignKeystore_pfx=/run/secrets/winCodeSignKeystore_pfx \
    macCodeSignKeystore_p12=/run/secrets/macCodeSignKeystore_p12 \
    winCodeSignKeystore_pswdfile=/run/secrets/winCodeSignKeystore_pswdfile \
    macCodeSignKeystore_pswdfile=/run/secrets/macCodeSignKeystore_pswdfile \
    Install4J_product_key_file=/run/secrets/Install4J_product_key_file

#
# these are to be overridden for a particular context
#
ENV compiler_updateSiteBaseUrl=http://vcell.org/webstart/Test \
    compiler_vcellIcnsFile=/install/icons/vcell.icns \
    compiler_mavenRootDir=/vcellclient \
    compiler_softwareVersionString=Test_Version_6.2_build_7 \
    compiler_Site=Test \
    compiler_vcellVersion=6.2 \
    compiler_vcellBuild=7 \
    compiler_rmiHosts=vcell-rmi-alpha.cam.uchc.edu:40108 \
    compiler_bioformatsJarFile=vcell-bioformats-0.0.3-SNAPSHOT-jar-with-dependencies.jar \
    compiler_bioformatsJarDownloadURL=http://vcell.org/webstart/vcell-bioformats-0.0.3-SNAPSHOT-jar-with-dependencies.jar \
    compiler_applicationId=1471-8022-1038-5555 \
    macJre=macosx-amd64-1.8.0_141.tar.gz \
    win64Jre=windows-amd64-1.8.0_141.tar.gz \
    win32Jre=windows-x86-1.8.0_141.tar.gz \
    linux64Jre=linux-amd64-1.8.0_66.tar.gz \
    linux32Jre=linux-x86-1.8.0_66.tar.gz

ENTRYPOINT [ "/config/build_installers.sh" ]