FROM maven:3.5-jdk-8-alpine as build
COPY . /app/
WORKDIR /app
RUN mvn clean install dependency:copy-dependencies


FROM schaff/vcell-solvers:release-0.0.4-dev

RUN apt-get install -y openjdk-8-jre-headless

RUN mkdir -p /usr/local/app
WORKDIR /usr/local/app

COPY --from=build \
     /app/vcell-server/target/vcell-server-0.0.1-SNAPSHOT.jar \
     /app/vcell-server/target/maven-jars/*.jar \
     ./lib/

COPY --from=build /app/nativelibs/linux64 ./nativelibs/linux64
COPY --from=build /app/solvers.sh ./solvers.sh

ENV softwareVersion=JimMac_Version_6.2_build_99 \
	serverid=TEST2 \
    jmsurl=failover:(tcp://activemq:61616) \
    jmsuser=clientUser \
    jmspswd=dummy \
    solverprimarydata=/simdata/ \
    mongodbhost=localhost \
    jmsblob_minsize=100000

VOLUME /simdata
VOLUME /htclogs

ENTRYPOINT ./solvers.sh
