FROM maven:3.5-jdk-8-alpine as build
ADD . /app
WORKDIR /app
RUN mvn clean install dependency:copy-dependencies


FROM nimmis/java-centos:openjdk-8-jre-headless

RUN mkdir -p /usr/local/app/lib
WORKDIR /usr/local/app

COPY --from=build \
     ./vcell-server/target/vcell-server-0.0.1-SNAPSHOT.jar \
     ./vcell-server/target/maven-jars/* \
     ./vcell-oracle/target/vcell-oracle-0.0.1-SNAPSHOT.jar \
     ./vcell-oracle/target/maven-jars/* \
     ./ojdbc6/src/ojdbc6.jar \
     ./ucp/src/ucp.jar \
     ./lib/

ENV softwareVersion=JimMac_Version_6.2_build_99 \
    serverid=TEST2 \
    dburl=jdbc:oracle:thin:@VCELL-DB.cam.uchc.edu:1521/vcelldborcl.cam.uchc.edu \
    dbdriver=oracle.jdbc.driver.OracleDriver \
    dbuser=vcell \
    dbpswdfile=/run/secrets/dbpswd \
    jmsurl=failover:(tcp://activemq:61616) \
    jmsuser=clientUser \
    jmspswdfile=/run/secrets/jmspswd \
    rmihost=localhost \
    jmsblob_minsize=100000

EXPOSE 8088

ENTRYPOINT java \
		-Dvcell.softwareVersion="${softwareVersion}" \
		-Djava.rmi.server.hostname="${rmihost}" \
		-Dvcell.server.id="${serverid}" \
		-Dvcell.installDir=/usr/local/app \
		-Dvcell.server.dbConnectURL="${dburl}" \
		-Dvcell.server.dbDriverName="${dbdriver}" \
		-Dvcell.server.dbUserid="${dbuser}" \
		-Dvcell.db.pswdfile="${dbpswdfile}" \
		-Dvcell.jms.url="${jmsurl}" \
		-Dvcell.jms.blobMessageUseMongo=true \
		-Dvcell.jms.blobMessageMinSize="${jmsblob_minsize}" \
		-Dvcell.jms.user="${jmsuser}" \
		-Dvcell.jms.pswdfile="${jmspswdfile}" \
		-Dvcell.mongodb.host=mongodb \
		-Dvcell.mongodb.port=27017 \
		-Dvcell.mongodb.database=test \
		-Djava.rmi.server.logCalls=true \
		-Dsun.rmi.server.exceptionTrace=true \
		-cp "./lib/*" cbit.vcell.message.server.bootstrap.LocalVCellBootstrap \
		"${rmihost}" 8088 messaging -
