#!/usr/bin/bash
#SBATCH --partition=vcell
#SBATCH --reservation=
#SBATCH --qos=vcell
#SBATCH -J V_REL_274631114_0_0
#SBATCH -o /share/apps/vcell3/htclogs/V_REL_274631114_0_0.slurm.log
#SBATCH -e /share/apps/vcell3/htclogs/V_REL_274631114_0_0.slurm.log
#SBATCH --mem=4096M
#SBATCH --no-kill
#SBATCH --no-requeue
# VCell SlurmProxy memory limit source='Exception NoSuchFileException used FALLBACK_MEM_LIMIT_MB'


TMPDIR=/scratch/vcell
if [ ! -e $TMPDIR ]; then mkdir -p $TMPDIR ; fi
echo `hostname`
export MODULEPATH=/isg/shared/modulefiles:/tgcapps/modulefiles
source /usr/share/Modules/init/bash
module load singularity/vcell-3.10.0
export SINGULARITY_CACHEDIR=/share/apps/vcell3/singularity/cachdir
export SINGULARITY_PULLFOLDER=/share/apps/vcell3/singularity/pullfolder
echo "job running on host `hostname -f`"
echo "id is `id`"
echo ENVIRONMENT
env

container_bindings="--bind /share/apps/vcell3/users:/simdata "
container_bindings+="--bind /scratch/vcell:/solvertmp "
container_bindings+="--bind /share/apps/vcell3/htclogs:/htclogs "
container_bindings+="--bind /share/apps/vcell7/users:/simdata_secondary "
container_env="--env java_mem_Xmx=4096M "
container_env+="--env jmshost_sim_internal=rke-wn-01.cam.uchc.edu "
container_env+="--env jmsport_sim_internal=31618 "
container_env+="--env jmsrestport_sim_internal=30163 "
container_env+="--env jmsuser=clientUser "
container_env+="--env jmspswd=dummy "
container_env+="--env jmsblob_minsize=100000 "
container_env+="--env mongodbhost_internal=rke-wn-01.cam.uchc.edu "
container_env+="--env mongodbport_internal=30019 "
container_env+="--env mongodb_database=test "
container_env+="--env primary_datadir_external=/share/apps/vcell3/users "
container_env+="--env secondary_datadir_external=/share/apps/vcell7/users "
container_env+="--env htclogdir_external=/share/apps/vcell3/htclogs "
container_env+="--env softwareVersion=Rel_Version_7.6.0_build_28 "
container_env+="--env serverid=REL "
solver_docker_name=ghcr.io/virtualcell/vcell-batch:7.6.0.43
solver_container_prefix="singularity run --containall ${container_bindings} ${container_env} docker://${solver_docker_name}"
batch_docker_name=ghcr.io/virtualcell/vcell-batch:7.6.0.43
batch_container_prefix="singularity run --containall ${container_bindings} ${container_env} docker://${batch_docker_name}"


sendFailureMsg() {
  ${batch_container_prefix}  --msg-userid clientUser --msg-password dummy --msg-host rke-wn-01.cam.uchc.edu --msg-port 31618 --msg-job-host `hostname` --msg-job-userid schaff --msg-job-simkey 274631114 --msg-job-jobindex 0 --msg-job-taskid 0 --msg-job-errmsg "$1" SendErrorMsg
  stat=$?
  if [[ $stat -ne 0 ]]; then
    echo 'failed to send error message, retcode=$stat'
  else
    echo 'sent failure message'
  fi
}


callExitProcessor( ) {
	"${batch_container_prefix} JavaPostprocessor64 274631114 schaff 17 0 0 $1 /share/apps/vcell3/htclogs/V_REL_274631114_0_0.slurm.sub "
}


"${solver_container_prefix} JavaSimExe64 /share/apps/vcell3/users/schaff/SimID_274631114_0__0.simtask.xml /share/apps/vcell3/users/schaff "
stat=$?
echo returned $stat
if [ $stat -ne 0 ]; then
	callExitProcessor $stat
	echo returning $stat to Slurm
	exit $stat
fi

callExitProcessor 0


#Following commands (if any) are read by JavaPostProcessor64