//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 03:55:47 PM EST 
//


package neuroml.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Choice of the various rate constant expressions allowed
 * 
 * <p>Java class for RateConstantEqnChoice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateConstantEqnChoice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="parameterised_hh" type="{http://morphml.org/channelml/schema}AkdEquation"/>
 *         &lt;element name="generic_equation_hh" type="{http://morphml.org/channelml/schema}GenericEquation"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateConstantEqnChoice", propOrder = {
    "parameterisedHh",
    "genericEquationHh"
})
public class RateConstantEqnChoice {

    @XmlElement(name = "parameterised_hh")
    protected AkdEquation parameterisedHh;
    @XmlElement(name = "generic_equation_hh")
    protected GenericEquation genericEquationHh;

    /**
     * Gets the value of the parameterisedHh property.
     * 
     * @return
     *     possible object is
     *     {@link AkdEquation }
     *     
     */
    public AkdEquation getParameterisedHh() {
        return parameterisedHh;
    }

    /**
     * Sets the value of the parameterisedHh property.
     * 
     * @param value
     *     allowed object is
     *     {@link AkdEquation }
     *     
     */
    public void setParameterisedHh(AkdEquation value) {
        this.parameterisedHh = value;
    }

    /**
     * Gets the value of the genericEquationHh property.
     * 
     * @return
     *     possible object is
     *     {@link GenericEquation }
     *     
     */
    public GenericEquation getGenericEquationHh() {
        return genericEquationHh;
    }

    /**
     * Sets the value of the genericEquationHh property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericEquation }
     *     
     */
    public void setGenericEquationHh(GenericEquation value) {
        this.genericEquationHh = value;
    }

}
