# coding: utf-8

"""
    VCell API

    VCell API

    The version of the OpenAPI document: 1.0.1
    Contact: vcell_support@uchc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from vcell_client.models.field_data_reference_info import FieldDataReferenceInfo

class TestFieldDataReferenceInfo(unittest.TestCase):
    """FieldDataReferenceInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldDataReferenceInfo:
        """Test FieldDataReferenceInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldDataReferenceInfo`
        """
        model = FieldDataReferenceInfo()
        if include_optional:
            return FieldDataReferenceInfo(
                reference_source_type = '',
                reference_source_name = '',
                application_name = '',
                simulation_name = '',
                ref_source_version_date = '',
                func_names = [
                    ''
                    ],
                ref_source_version_key = vcell_client.models.key_value.KeyValue(
                    value = 1.337, )
            )
        else:
            return FieldDataReferenceInfo(
        )
        """

    def testFieldDataReferenceInfo(self):
        """Test FieldDataReferenceInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
