# coding: utf-8

"""
    VCell API

    VCell API

    The version of the OpenAPI document: 1.0.1
    Contact: vcell_support@uchc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vcell_client.api.solver_resource_api import SolverResourceApi


class TestSolverResourceApi(unittest.TestCase):
    """SolverResourceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SolverResourceApi()

    def tearDown(self) -> None:
        pass

    def test_get_fv_solver_input(self) -> None:
        """Test case for get_fv_solver_input

        Retrieve finite volume input from SBML spatial model.
        """
        pass


if __name__ == '__main__':
    unittest.main()
