//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 03:55:47 PM EST 
//


package neuroml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import neuroml.morph.Cell;


/**
 * Cell with extensions for biophysics, and network functionality
 * 
 * <p>Java class for Level3Cell complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Level3Cell">
 *   &lt;complexContent>
 *     &lt;extension base="{http://morphml.org/morphml/schema}Cell">
 *       &lt;sequence>
 *         &lt;element name="biophysics" type="{http://morphml.org/neuroml/schema}Level3Biophysics" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Level3Cell", propOrder = {
    "biophysics"
})
public class Level3Cell
    extends Cell
{

    protected Level3Biophysics biophysics;

    /**
     * Gets the value of the biophysics property.
     * 
     * @return
     *     possible object is
     *     {@link Level3Biophysics }
     *     
     */
    public Level3Biophysics getBiophysics() {
        return biophysics;
    }

    /**
     * Sets the value of the biophysics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Level3Biophysics }
     *     
     */
    public void setBiophysics(Level3Biophysics value) {
        this.biophysics = value;
    }

}
