[tool.poetry]
name = "vcelldata"
version = "0.1.0"
description = ""
authors = ["Jim Schaff <schaff.jim@gmail.com>"]
readme = "README.md"
packages = [{ include = "vcelldata" }]


[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.9.0"
numexpr = "^2.9.0"
zarr = "^2.17.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
