apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data
  name: data
spec:
  selector:
    matchLabels:
      app: data
  replicas: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
        - name: data
          image: ghcr.io/virtualcell/vcell-data
          imagePullPolicy: "Always"
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "3000Mi"
#              cpu: "500m"
          envFrom:
            - configMapRef:
                name: data-config
          #          command: [ "/bin/sh", "-c", "env; cat /run/secrets/api-secrets/dbpswd" ]
          env:
            - name: jmspswdfile
              value: "/run/secrets/api-secrets/jmspswd"
            - name: dbpswdfile
              value: "/run/secrets/api-secrets/dbpswd"
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /run/secrets/api-secrets
              name: api-secrets
            - mountPath: /simdata
              name: primary-data-pvc
#            - mountPath: /share/apps/vcell12/users
#              name: data-claim2
            - mountPath: /simdata_secondary
              name: secondary-data-pvc
#            - mountPath: /exportdir
#              name: data-claim4
            - mountPath: /n5DataDir
              name: n5data-pvc

      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: api-secrets
          secret:
            items:
              - key: dbpswd
                path: dbpswd
              - key: jmspswd
                path: jmspswd
            secretName: api-secrets
        - name: primary-data-pvc
          persistentVolumeClaim:
            claimName: primary-data-pvc
        - name: secondary-data-pvc
          persistentVolumeClaim:
            claimName: secondary-data-pvc
        - name: n5data-pvc
          persistentVolumeClaim:
            claimName: n5data-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: data
  name: data
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 8000
  selector:
    app: data
