apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 0
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/swarm-vcellnet: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: dbdriver
              value: oracle.jdbc.driver.OracleDriver
            - name: dburl
              value: jdbc:oracle:thin:@vcell-oracle.cam.uchc.edu:1521/ORCLPDB1
            - name: dbuser
              value: vcell
            - name: jmshost_int_internal
              value: activemqint
            - name: jmsport_int_internal
              value: "61616"
            - name: jmsuser
              value: clientUser
            - name: mongodb_database
              value: test
            - name: mongodb_host_internal
              value: mongodb
            - name: mongodb_port_internal
              value: "27017"
            - name: serverid
              value: TEST
            - name: softwareVersion
              value: Test_Version_7.5.0_build_1234
          image: ghcr.io/virtualcell/vcell-db:dev
          name: db
          ports:
            - containerPort: 8000
              hostPort: 5003
              protocol: TCP
          resources:
            limits:
              memory: "2097152e3"
            requests:
              memory: "1048576e3"
          volumeMounts:
            - mountPath: /run/secrets/dbpswd
              name: dbpswd
            - mountPath: /run/secrets/jmspswd
              name: jmspswd
      restartPolicy: Always
      volumes:
        - name: dbpswd
          secret:
            items:
              - key: dbpswd
                path: dbpswd
            secretName: dbpswd
        - name: jmspswd
          secret:
            items:
              - key: jmspswd
                path: jmspswd
            secretName: jmspswd
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
    - name: "5003"
      port: 5003
      targetPort: 8000
  selector:
    io.kompose.service: db
