apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 0
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: ghcr.io/virtualcell/vcell-db
          imagePullPolicy: "Always"
          resources:
            requests:
              memory: "1000Mi"
              cpu: "200m"
            limits:
              memory: "2000Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: db-config
#          command: [ "/bin/sh", "-c", "env; cat /run/secrets/api-secrets/dbpswd" ]
          ports:
            - containerPort: 8000
              hostPort: 5003
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets/api-secrets
              name: api-secrets
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: api-secrets
          secret:
            items:
              - key: dbpswd
                path: dbpswd
              - key: jmspswd
                path: jmspswd
            secretName: api-secrets
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
    - name: "5003"
      port: 5003
      targetPort: 8000
  selector:
    app: db
