apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: ghcr.io/virtualcell/vcell-mongo
          imagePullPolicy: "Always"
          ports:
            - containerPort: 27017
              hostPort: 27020
              protocol: TCP
          resources:
            limits:
              memory: "1500Mi"
            requests:
              memory: "1000Mi"
          volumeMounts:
            - mountPath: /data/db
              name: mongodbdata
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: mongodbdata
          persistentVolumeClaim:
            claimName: mongodbdata
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
    - name: "27020"
      port: 27020
      targetPort: 27017
  selector:
    app: mongodb
