apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sched
  name: sched
spec:
  selector:
    matchLabels:
      app: sched
  replicas: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sched
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10000
        fsGroup: 10000
      containers:
        - name: sched
          image: ghcr.io/virtualcell/vcell-sched
          imagePullPolicy: "Always"
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "2000Mi"
#              cpu: "500m"
          envFrom:
            - configMapRef:
                name: sched-config
          #          command: [ "/bin/sh", "-c", "env; cat /run/secrets/api-secrets/dbpswd" ]
          env:
            - name: batchuserkeyfile
              value: "/run/secrets/batchuserkeyfile/ssh-privatekey"
            - name: jmspswdfile
              value: "/run/secrets/api-secrets/jmspswd"
            - name: dbpswdfile
              value: "/run/secrets/api-secrets/dbpswd"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: api-secrets
              mountPath: /run/secrets/api-secrets
            - name: batchuserkeyfile
              mountPath: /run/secrets/batchuserkeyfile

            - name: nfs-primary-pvc
              mountPath: /htclogs
              subPath: htclogs
            - name: nfs-primary-pvc
              mountPath: /simdata
              subPath: users
            - name: nfs-archive-pvc
              mountPath: /share/apps/vcell12/users
              subPath: users
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: api-secrets
          secret:
            items:
              - key: dbpswd
                path: dbpswd
              - key: jmspswd
                path: jmspswd
            secretName: api-secrets
        - name: batchuserkeyfile
          secret:
            defaultMode: 256
            items:
              - key: ssh-privatekey
                path: ssh-privatekey
            secretName: vcell-ssh-secret
        - name: nfs-primary-pvc
          persistentVolumeClaim:
            claimName: nfs-primary-pvc
        - name: nfs-archive-pvc
          persistentVolumeClaim:
            claimName: nfs-archive-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sched
  name: sched
spec:
  ports:
    - name: "5004"
      port: 5004
      targetPort: 8000
  selector:
    app: sched
