apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: sched
  name: sched
spec:
  replicas: 0
  selector:
    matchLabels:
      io.kompose.service: sched
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/swarm-vcellnet: "true"
        io.kompose.service: sched
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: zone
                    operator: In
                    values:
                      - INTERNAL
      containers:
        - env:
            - name: batchhost
              value: hpc-ext-1.cam.uchc.edu,hpc-ext-2.cam.uchc.edu,hpc-ext-3.cam.uchc.edu,hpc-ext-4.cam.uchc.edu
            - name: batchsystem
              value: SLURM
            - name: batchuser
              value: vcell
            - name: dbdriver
              value: oracle.jdbc.driver.OracleDriver
            - name: dburl
              value: jdbc:oracle:thin:@vcell-oracle.cam.uchc.edu:1521/ORCLPDB1
            - name: dbuser
              value: vcell
            - name: htcnodelist
            - name: jmshost_int_internal
              value: activemqint
            - name: jmshost_sim_internal
              value: activemqsim
            - name: jmsport_int_internal
              value: "61616"
            - name: jmsport_sim_internal
              value: "61616"
            - name: jmsuser
              value: clientUser
            - name: maxJobsPerScan
              value: "100"
            - name: maxOdeJobsPerUser
              value: "100"
            - name: maxPdeJobsPerUser
              value: "40"
            - name: mongodb_database
              value: test
            - name: mongodb_host_internal
              value: mongodb
            - name: mongodb_port_internal
              value: "27017"
            - name: serverid
              value: TEST
            - name: simdataCacheSize
              value: "10000000"
            - name: slurm_cmd_sacct
              value: sacct
            - name: slurm_cmd_sbatch
              value: sbatch
            - name: slurm_cmd_scancel
              value: scancel
            - name: slurm_cmd_squeue
              value: squeue
            - name: slurm_partition
              value: vcell
            - name: slurm_partition_pu
              value: vcellpu
            - name: slurm_reservation
              value: vcell
            - name: slurm_reservation_pu
              value: vcellpu
            - name: softwareVersion
              value: Test_Version_7.5.0_build_1234
            - name: vcell_ssh_cmd_cmdtimeout
              value: "10000"
            - name: vcell_ssh_cmd_restoretimeout
              value: "5"
          image: ghcr.io/virtualcell/vcell-sched:dev
          name: sched
          ports:
            - containerPort: 8000
              hostPort: 5004
              protocol: TCP
          resources:
            limits:
              memory: "2097152e3"
            requests:
              memory: "1048576e3"
          volumeMounts:
            - mountPath: /run/secrets/dbpswd
              name: dbpswd
            - mountPath: /run/secrets/jmspswd
              name: jmspswd
            - mountPath: /run/secrets/batchuserkeyfile
              name: batchuserkeyfile
            - mountPath: /simdata
              name: sched-claim0
            - mountPath: /share/apps/vcell12/users
              name: sched-claim1
            - mountPath: /htclogs
              name: sched-claim2
      restartPolicy: Always
      volumes:
        - name: dbpswd
          secret:
            items:
              - key: dbpswd
                path: dbpswd
            secretName: dbpswd
        - name: jmspswd
          secret:
            items:
              - key: jmspswd
                path: jmspswd
            secretName: jmspswd
        - name: batchuserkeyfile
          secret:
            defaultMode: 256
            items:
              - key: batchuserkeyfile
                path: batchuserkeyfile
            secretName: batchuserkeyfile
        - name: sched-claim0
          persistentVolumeClaim:
            claimName: sched-claim0
        - name: sched-claim1
          persistentVolumeClaim:
            claimName: sched-claim1
        - name: sched-claim2
          persistentVolumeClaim:
            claimName: sched-claim2
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: sched
  name: sched
spec:
  ports:
    - name: "5004"
      port: 5004
      targetPort: 8000
  selector:
    io.kompose.service: sched
