apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: submit
  name: submit
spec:
  selector:
    matchLabels:
      app: submit
  replicas: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: submit
    spec:
      containers:
        - name: submit
          image: ghcr.io/virtualcell/vcell-submit
          imagePullPolicy: "Always"
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "2000Mi"
#              cpu: "500m"
          envFrom:
            - configMapRef:
                name: submit-config
          #          command: [ "/bin/sh", "-c", "env; cat /run/secrets/api-secrets/dbpswd" ]
          env:
            - name: batchuserkeyfile
              value: "/run/secrets/batchuserkeyfile/ssh-privatekey"
            - name: jmspswdfile
              value: "/run/secrets/api-secrets/jmspswd"
            - name: dbpswdfile
              value: "/run/secrets/api-secrets/dbpswd"
          ports:
            - containerPort: 8000
            - containerPort: 8877
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets/api-secrets
              name: api-secrets
            - mountPath: /run/secrets/batchuserkeyfile
              name: batchuserkeyfile
            - mountPath: /simdata
              name: primary-data-pvc
#            - mountPath: /share/apps/vcell12/users
#              name: sched-claim1
            - mountPath: /simdata_secondary
              name: secondary-data-pvc
#            - mountPath: /htclogs
#              name: submit-claim2
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: api-secrets
          secret:
            items:
              - key: dbpswd
                path: dbpswd
              - key: jmspswd
                path: jmspswd
            secretName: api-secrets
        - name: batchuserkeyfile
          secret:
            defaultMode: 256
            items:
              - key: ssh-privatekey
                path: ssh-privatekey
            secretName: vcell-ssh-secret
        - name: primary-data-pvc
          persistentVolumeClaim:
            claimName: primary-data-pvc
        - name: secondary-data-pvc
          persistentVolumeClaim:
            claimName: secondary-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: submit
  name: submit
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 8000
    - name: "8877"
      port: 8877
      targetPort: 8877
  selector:
    app: submit
