#!/bin/bash

printusage() {
	echo "Usage: JavaSimExe64 simTaskFile userdir"
	exit 1
}

# main code
if [ "$#" != "2" ] ; then 
	printusage
fi

#
# include common variable definitions
#
DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. $DIR/vcell.include

#
# make sure no variables are left unset
#
shopt -s -o nounset

jvmprop="-Xmx${javasolver_memoryMB}M  -Dvcell.propertyfile=${common_propertyfile} -Djava.io.tmpdir=${common_siteTmpDir}"

arguments=$*

echo "starting java solver"

nice ${common_jre} -cp ${common_jvm_jars} ${jvmprop} ${javasolver_mainclass} ${arguments}

echo "java solver returned"

exit 0

