#!/bin/bash

printusage() {
	echo "Usage: JavaPreprocessor64 [simTaskFile] [userdir] <parallel Dir>"
	exit 1
}

# main code
if [ "$#" < "3" ] ; then 
	printusage
fi

#
# include common variable definitions
#
DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. $DIR/vcell.include
. $DIR/server.include

#
# make sure no variables are left unset
#
shopt -s -o nounset

jvmprop="-Xmx${preprocessor_memoryMB}M  -Dvcell.propertyfile=${common_propertyfile} -Djava.io.tmpdir=${common_siteTmpDir}"
jvmprop="${jvmprop} -Dlog4jConfigurationFile=${common_siteCfgDir}/log4jJavaPreProcessor.properties"

setupJavaPrefs

arguments=$*

echo "starting preprocessor"

nice ${common_jre} -cp ${common_jvm_jars} ${jvmprop} ${preprocessor_mainclass} ${arguments}

echo "preprocessor returned"

exit 0

