#!/bin/bash

printusage() {
	echo "Usage: JavaPostprocessor64 simKey userid userKey jobindex taskid solverExitCode"
	exit 1
}

# main code
if [ $# -lt 6 ] ; then
	printusage
fi

#
# include common variable definitions
#
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. $DIR/vcell.include
. $DIR/server.include

#
# make sure no variables are left unset
#
shopt -s -o nounset

jvmprop="-Xmx${postprocessor_memoryMB}M  -Dvcell.propertyfile=${common_propertyfile} -Djava.io.tmpdir=${common_siteTmpDir}"
jvmprop="${jvmprop} -Dlog4jConfigurationFile=${common_siteCfgDir}/log4jJavaPostProcessor.properties"
jvmprop="${jvmprop} -Dvcell.lib=${common_siteNativelibsDir}"

setupJavaPrefs

arguments=$*

echo "starting postprocessor"

nice ${common_jre} -cp ${common_jvm_jars} ${jvmprop} ${postprocessor_mainclass} ${arguments} | tee -ai /dev/stderr |grep -q 'os::commit_memory'
if [ $? -eq 0 ]; then
	echo "MEMORY FAILURE DETECTED"
fi

echo "postprocessor returned"

exit 0

