#!/usr/bin/env bash


DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. $DIR/vcell.include

shopt -s -o nounset

SSH_OPT='-o ConnectTimeout=10'

localscript="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/vcellstop_local"

echo ""
echo "===== INSTRUCTIONS TO STOP VCELL ================"
echo ""

echo "ssh $SSH_OPT $vcellservice_host '${localscript}'"
#ssh $SSH_OPT $vcellservice_host '${localscript}'

echo "ssh $SSH_OPT $bootstrap_host '${localscript}'"
#ssh $SSH_OPT $bootstrap_host '${localscript}'

echo "ssh $SSH_OPT $vcellapi_host '${localscript}'"
#ssh $SSH_OPT $vcellapi_host '${localscript}'
