#!/bin/bash 
# delay for load balancing / staggering 
STARTUP_DELAY=${1:-0}
sleep $STARTUP_DELAY


#
# include common variable definitions
#

DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. $DIR/vcell.include
. $DIR/server.include


makelogname master
#
# make sure no variables are left unset
#
shopt -s -o nounset

#
# Process label for identifying service from ps -ef output
#
procLabel="-DprocessLabel=${vcellservice_processLabel}"

#
# Java Management Extensions
#
jmxargs="-Dcom.sun.management.jmxremote"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.authenticate=false"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.port=${vcellservice_jmxport}"
jmxargs="${jmxargs} -Dcom.sun.management.jmxremote.ssl=false"
jmxargs="${jmxargs} -Djava.rmi.server.hostname=${vcellservice_jmxhost}"
jmxargs="${jmxargs} -XX:+UseG1GC -XX:MaxGCPauseMillis=500" 
#jmxargs="${jmxargs} -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000"

jvmprop="-Xmx${vcellservice_memoryGB}G"
jvmprop="${jvmprop} -Dvcell.propertyfile=${common_propertyfile}"
jvmprop="${jvmprop} -Djava.io.tmpdir=${common_siteTmpDir}"
jvmprop="${jvmprop} -Dlog4jConfigurationFile=${common_siteCfgDir}/log4jvcellservice.properties"
jvmprop="${jvmprop} -Dvcell.lib=${common_siteNativelibsDir}"

setupJavaPrefs

arguments="123 ${common_logdir} ${common_batchSystemType}"

if [ "$vcellservice_htc_usessh" = true ] ; then
	arguments="$arguments $vcellservice_htc_ssh_host $vcellservice_htc_ssh_user $vcellservice_htc_ssh_dsaKeyFile"
fi

#
# IMPORTANT:  ${procLabel} must be first because we are filtering on it for the kill script in DeployVCell.
#
{

nohup ${common_jre} ${procLabel} ${jmxargs} -cp ${common_jvm_jars} ${jvmprop} ${vcellservice_mainclass} ${arguments} &

#record pid of service
echo -n "$! " >${common_logdir}/servicepid
hostname >>${common_logdir}/servicepid

exit 0
} > $STARTUPLOG 2>&1

