#!/bin/bash

DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. $DIR/vcell.include

# make sure no variables are left unset
shopt -s -o nounset

export common_siteCfgDir
export vcellapi_host
export vcellservice_host
export bootstrap_rmihost
export vcellservice_processLabel
export bootstrap_http_processLabel
export bootstrap_high_processLabel
export vcellapi_processLabel

python $DIR/vcell.py $@

