-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.3
-- Copyright 2000-2024 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=vcell-oracle.cam.uchc.edu;service_name=ORCLPDB1;port=1521

SET client_encoding TO 'UTF8';

SET search_path = vcell,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS ts_lock_trig ON vc_tftestsuite CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_ts_lock_trig() RETURNS trigger AS $BODY$
DECLARE
lockState bigint;
BEGIN
  BEGIN

   if OLD.islocked != 0
   then
   RAISE EXCEPTION '%', 'Test Suite ' || OLD.tsversion || ' locked' USING ERRCODE = '45100';
   end if;

  END;
IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_ts_lock_trig() FROM PUBLIC;

CREATE TRIGGER ts_lock_trig
	BEFORE UPDATE OR DELETE ON vc_tftestsuite 
 FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_ts_lock_trig();

