/*
 * Copyright (C) 1999-2011 University of Connecticut Health Center
 *
 * Licensed under the MIT License (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *  http://www.opensource.org/licenses/mit-license.php
 */

package cbit.vcell.graph;
import cbit.gui.graph.*;
import cbit.vcell.model.*;
import java.util.*;
import java.awt.*;
/**
 * This class was generated by a SmartGuide.
 * 
 */
public abstract class ModelCartoon extends GraphModel implements java.beans.PropertyChangeListener{
	private Model fieldModel = null;

/**
 * Insert the method's description here.
 * Creation date: (5/13/2003 2:30:25 PM)
 */
public ModelCartoon() {}


/**
 * Insert the method's description here.
 * Creation date: (5/13/2003 9:46:54 AM)
 * @return cbit.vcell.model.Model
 */
public Model getModel() {
	return fieldModel;
}


/**
 * Insert the method's description here.
 * Creation date: (5/13/2003 9:46:54 AM)
 * @param newFieldModel cbit.vcell.model.Model
 */
public void setModel(Model newFieldModel) {
	
	Model oldModel = fieldModel;
	
	if(oldModel != null){
		fieldModel.removePropertyChangeListener(this);
	}
	fieldModel = newFieldModel;
	if(fieldModel != null){
		fieldModel.removePropertyChangeListener(this);
		fieldModel.addPropertyChangeListener(this);
	}
	refreshAll();
	firePropertyChange("model",oldModel,newFieldModel);
}
}
