apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: api-claim2
  name: api-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
