#!/bin/bash
#SBATCH --job-name=VREL999999999
#SBATCH --output=/home/FCAM/vasilescu/vcell-batch-job/logs/submit_vcell_batch.log
#SBATCH --ntasks=4              # how many tasks to run in parallel
#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --time=01:00:00
#SBATCH --partition=vcell
#SBATCH --qos=vcell

BASE_DIR=/home/FCAM/vasilescu/vcell-batch-job
CONTAINER_IMAGE=$BASE_DIR/container/vcell-batch_7.7.0.30.sif
INPUT_DIR=$BASE_DIR/input
OUTPUT_DIR=$BASE_DIR/output
LOG_DIR=$BASE_DIR/logs
SIMXML=$INPUT_DIR/SimID_999999999_0__0.simtask.xml

echo "=== [$(date)] === SLURM job started on node $(hostname)"
sleep 15

echo "[Preprocess] Running JavaPreprocessor64..."
singularity exec \
  --bind $INPUT_DIR:$INPUT_DIR \
  --bind $OUTPUT_DIR:$OUTPUT_DIR \
  $CONTAINER_IMAGE \
  JavaPreprocessor64 $SIMXML $OUTPUT_DIR

echo "[Simulate] Running langevin_x64..."
singularity exec \
  --bind $INPUT_DIR:$INPUT_DIR \
  --bind $OUTPUT_DIR:$OUTPUT_DIR \
  $CONTAINER_IMAGE \
  langevin_x64 simulate \
    $INPUT_DIR/SimID_999999999_0_.langevinInput \
    0 \
    --output-log=$OUTPUT_DIR/SimID_999999999_0__0.log \
    --vc-print-status &
pid0=$!

singularity exec \
  --bind $INPUT_DIR:$INPUT_DIR \
  --bind $OUTPUT_DIR:$OUTPUT_DIR \
  $CONTAINER_IMAGE \
  langevin_x64 simulate \
    $INPUT_DIR/SimID_999999999_0_.langevinInput \
    1 \
    --output-log=$OUTPUT_DIR/SimID_999999999_0__1.log \
    --vc-print-status &
pid1=$!

singularity exec \
  --bind $INPUT_DIR:$INPUT_DIR \
  --bind $OUTPUT_DIR:$OUTPUT_DIR \
  $CONTAINER_IMAGE \
  langevin_x64 simulate \
    $INPUT_DIR/SimID_999999999_0_.langevinInput \
    2 \
    --output-log=$OUTPUT_DIR/SimID_999999999_0__2.log \
    --vc-print-status &
pid2=$!

wait $pid0
wait $pid1
wait $pid2

echo "[Postprocess] Running JavaPostprocessor64..."
singularity exec \
  --bind $OUTPUT_DIR:$OUTPUT_DIR \
  $CONTAINER_IMAGE \
  JavaPostprocessor64 999999999 vasilescu 17 0 0 10 $SLURM_JOB_SCRIPT

echo "=== [$(date)] === SLURM job completed"
