#!/bin/bash
#SBATCH --job-name=VREL999999999
#SBATCH --output=/home/FCAM/vasilescu/vcell-batch-job/logs/submit_vcell_batch.log
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --time=01:00:00
#SBATCH --partition=vcell
#SBATCH --qos=vcell

BASE_DIR=/home/FCAM/vasilescu/vcell-batch-job
CONTAINER_IMAGE=$BASE_DIR/container/vcell-batch_7.7.0.28.sif
INPUT_DIR=$BASE_DIR/input
OUTPUT_DIR=$BASE_DIR/output
LOG_DIR=$BASE_DIR/logs
SIMXML=$INPUT_DIR/SimID_999999999_0__0.simtask.xml

echo "=== [$(date)] === SLURM job started on node $(hostname)"
sleep 15

echo "[Preprocess] Running JavaPreprocessor64..."

java --version

echo "=== [$(date)] === SLURM job completed"
