#!/bin/bash

printusage() {
	echo "Usage: JavaSimExe64 simTaskFileName"
	exit 1
}

# main code
if [ "$#" != "1" ] ; then 
	printusage
fi

simTaskFileName=$1

#
# make sure no variables are left unset
#
shopt -s -o nounset

javasolver_mainclass=cbit.vcell.message.server.sim.JavaSimulationExecutable

jvmprop="-Djava.io.tmpdir=/tmp"
jvmprop="${jmsprop} -Dvcell.jms.url=${jmsurl}"
jvmprop="${jmsprop} -Dvcell.jms.user=${jmsuser}"
jvmprop="${jmsprop} -Dvcell.jms.pswd=${jmspswd}"
jvmprop="${jmsprop} -Dvcell.primarySimdatadir=/simdata"
jvmprop="${jmsprop} -Dvcell.secondarySimdatadir=/simdata"
jvmprop="${jmsprop} -Dvcell.server.id=${serverid}"
jvmprop="${jmsprop} -Dvcell.softwareVersion=${softwareVersion}"


arguments="/simdata/$simTaskFileName /simdata"

echo "starting java solver"

nice java ${jvmprop} ${javasolver_mainclass} ${arguments}

echo "java solver returned"

exit 0

