#!/bin/bash

printusage() {
	echo "Usage: JavaPreprocessor64 simTaskFileName [parallel_dir]"
	exit 1
}

# main code
if [[ $# -eq 0 ]] ; then 
	printusage
	exit 1
fi

#
# make sure no variables are left unset
#
shopt -s -o nounset

preprocessor_mainclass="cbit.vcell.message.server.sim"

jvmprop="-Djava.io.tmpdir=/tmp"
jvmprop="${jvmprop} -Dvcell.jms.url=${jmsurl}"
jvmprop="${jvmprop} -Dvcell.jms.user=${jmsuser}"
jvmprop="${jvmprop} -Dvcell.jms.pswd=${jmspswd}"
jvmprop="${jvmprop} -Dvcell.primarySimdatadir=/simdata"
jvmprop="${jvmprop} -Dvcell.secondarySimdatadir=/simdata"
jvmprop="${jvmprop} -Dvcell.server.id=${serverid}"
jvmprop="${jvmprop} -Dvcell.softwareVersion=${softwareVersion}"

simTaskFileName=$1
arguments=/simdata/$simTaskFileName /simdata
if [[ $# -eq 2 ]] ; then
	parallel_dir=$2
	arguments=${arguments} ${parallel_dir}
fi

echo "starting preprocessor"

nice java ${jvmprop} ${preprocessor_mainclass} ${arguments} 

echo "preprocessor returned"

exit 0

