#!/bin/bash

printusage() {
	echo "Usage: JavaPostprocessor64 simKey userid userKey jobindex taskid solverExitCode"
	exit 1
}

# main code
if [ $# -lt 6 ] ; then
	printusage
fi

#
# make sure no variables are left unset
#
shopt -s -o nounset

postprocessor_mainclass=cbit.vcell.message.server.sim

jvmprop="-Djava.io.tmpdir=/tmp"
jvmprop="${jvmprop} -Dvcell.jms.url=${jmsurl}"
jvmprop="${jvmprop} -Dvcell.jms.user=${jmsuser}"
jvmprop="${jvmprop} -Dvcell.jms.pswd=${jmspswd}"
jvmprop="${jvmprop} -Dvcell.primarySimdatadir=/simdata"
jvmprop="${jvmprop} -Dvcell.secondarySimdatadir=/simdata"
jvmprop="${jvmprop} -Dvcell.server.id=${serverid}"
jvmprop="${jvmprop} -Dvcell.softwareVersion=${softwareVersion}"
jvmprop="${jvmprop} -Dvcell.lib=/usr/local/app/nativelibs/linux64"

arguments=$*

echo "starting postprocessor"

nice java ${jvmprop} ${postprocessor_mainclass} ${arguments} | tee -ai /dev/stderr |grep -q 'os::commit_memory'
if [ $? -eq 0 ]; then
	echo "MEMORY FAILURE DETECTED"
fi

echo "postprocessor returned"

exit 0

