#!/bin/bash

printusage() {
	echo "Usage: JavaPreprocessor64 simTaskFileName [parallel_dir]"
	exit 1
}
echo "JavaPreprocessor64 $@"

# main code
if [[ $# -eq 0 ]] ; then 
	printusage
	exit 1
fi

#
# make sure no variables are left unset
#
shopt -s -o nounset

preprocessor_mainclass=cbit.vcell.message.server.sim.SolverPreprocessor

jvmprop="-Djava.io.tmpdir=/tmp"
jvmprop="${jvmprop} -Dvcell.installDir=${installdir}"
jvmprop="${jvmprop} -Dvcell.jms.host.internal=${jmshost_internal}"
jvmprop="${jvmprop} -Dvcell.jms.port.internal=${jmsport_internal}"
jvmprop="${jvmprop} -Dvcell.jms.restport.internal=${jmsrestport_internal}"
jvmprop="${jvmprop} -Dvcell.jms.host.external=${jmshost_internal}"
jvmprop="${jvmprop} -Dvcell.jms.port.external=${jmsport_internal}"
jvmprop="${jvmprop} -Dvcell.jms.restport.external=${jmsrestport_internal}"
jvmprop="${jvmprop} -Dvcell.jms.user=${jmsuser}"
jvmprop="${jvmprop} -Dvcell.jms.password=${jmspswd}"
jvmprop="${jvmprop} -Dvcell.jms.blobMessageUseMongo=${blob_message_use_mongo}"
jvmprop="${jvmprop} -Dvcell.primarySimdatadir.internal=${datadir_internal}"
jvmprop="${jvmprop} -Dvcell.secondarySimdatadir.internal=${datadir_internal}"
jvmprop="${jvmprop} -Dvcell.primarySimdatadir.external=${datadir_external}"
jvmprop="${jvmprop} -Dvcell.secondarySimdatadir.external=${datadir_external}"
jvmprop="${jvmprop} -Dvcell.server.id=${serverid}"
jvmprop="${jvmprop} -Dvcell.softwareVersion=${softwareVersion}"
jvmprop="${jvmprop} -Dvcell.mongodb.database=${mongodb_database}"
jvmprop="${jvmprop} -Dvcell.mongodb.host.internal=${mongodbhost_internal}"
jvmprop="${jvmprop} -Dvcell.mongodb.port.internal=${mongodbport_internal}"

arguments=$*

echo "starting preprocessor"

nice java ${jvmprop} ${preprocessor_mainclass} ${arguments} 

echo "preprocessor returned"

exit 0

