/*
 * VCell API
 * VCell API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.vcell.restclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.vcell.restclient.model.User;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for GroupAccessSome
 */
public class GroupAccessSomeTest {
    private final GroupAccessSome model = new GroupAccessSome();

    /**
     * Model tests for GroupAccessSome
     */
    @Test
    public void testGroupAccessSome() {
        // TODO: test GroupAccessSome
    }

    /**
     * Test the property 'groupid'
     */
    @Test
    public void groupidTest() {
        // TODO: test groupid
    }

    /**
     * Test the property 'hash'
     */
    @Test
    public void hashTest() {
        // TODO: test hash
    }

    /**
     * Test the property 'groupMembers'
     */
    @Test
    public void groupMembersTest() {
        // TODO: test groupMembers
    }

    /**
     * Test the property 'hiddenMembers'
     */
    @Test
    public void hiddenMembersTest() {
        // TODO: test hiddenMembers
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'hiddenGroupMembers'
     */
    @Test
    public void hiddenGroupMembersTest() {
        // TODO: test hiddenGroupMembers
    }

    /**
     * Test the property 'normalGroupMembers'
     */
    @Test
    public void normalGroupMembersTest() {
        // TODO: test normalGroupMembers
    }

}
