/*
 * VCell API
 * VCell API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.vcell.restclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.vcell.restclient.model.BioModelSummary;
import org.vcell.restclient.model.GeometrySummary;
import org.vcell.restclient.model.MathModelSummary;
import org.vcell.restclient.model.VCImageSummary;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for VCInfoContainerSummary
 */
public class VCInfoContainerSummaryTest {
    private final VCInfoContainerSummary model = new VCInfoContainerSummary();

    /**
     * Model tests for VCInfoContainerSummary
     */
    @Test
    public void testVCInfoContainerSummary() {
        // TODO: test VCInfoContainerSummary
    }

    /**
     * Test the property 'bioModelSummaries'
     */
    @Test
    public void bioModelSummariesTest() {
        // TODO: test bioModelSummaries
    }

    /**
     * Test the property 'mathModelSummaries'
     */
    @Test
    public void mathModelSummariesTest() {
        // TODO: test mathModelSummaries
    }

    /**
     * Test the property 'geometrySummaries'
     */
    @Test
    public void geometrySummariesTest() {
        // TODO: test geometrySummaries
    }

    /**
     * Test the property 'vcImageSummaries'
     */
    @Test
    public void vcImageSummariesTest() {
        // TODO: test vcImageSummaries
    }

}
