/*
 * VCell API
 * VCell API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.vcell.restclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.vcell.restclient.model.KeyValue;
import org.vcell.restclient.model.User;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for VCSimulationIdentifier
 */
public class VCSimulationIdentifierTest {
    private final VCSimulationIdentifier model = new VCSimulationIdentifier();

    /**
     * Model tests for VCSimulationIdentifier
     */
    @Test
    public void testVCSimulationIdentifier() {
        // TODO: test VCSimulationIdentifier
    }

    /**
     * Test the property 'simulationKey'
     */
    @Test
    public void simulationKeyTest() {
        // TODO: test simulationKey
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'iD'
     */
    @Test
    public void iDTest() {
        // TODO: test iD
    }

}
