/*
 * VCell API
 * VCell API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.vcell.restclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for VersionFlag
 */
public class VersionFlagTest {
    private final VersionFlag model = new VersionFlag();

    /**
     * Model tests for VersionFlag
     */
    @Test
    public void testVersionFlag() {
        // TODO: test VersionFlag
    }

    /**
     * Test the property 'versionFlag'
     */
    @Test
    public void versionFlagTest() {
        // TODO: test versionFlag
    }

    /**
     * Test the property 'intValue'
     */
    @Test
    public void intValueTest() {
        // TODO: test intValue
    }

    /**
     * Test the property 'archived'
     */
    @Test
    public void archivedTest() {
        // TODO: test archived
    }

    /**
     * Test the property 'current'
     */
    @Test
    public void currentTest() {
        // TODO: test current
    }

    /**
     * Test the property 'published'
     */
    @Test
    public void publishedTest() {
        // TODO: test published
    }

}
