package org.vcell.sedml.testsupport;

@SuppressWarnings("unused")
public enum FailureType {
    ARRAY_INDEX_OUT_OF_BOUNDS,
    BAD_EULER_FORWARD,
    DIVIDE_BY_ZERO,
    EXPRESSIONS_DIFFERENT,
    EXPRESSION_BINDING,
    GEOMETRY_SPEC_DIFFERENT,
    HDF5_FILE_ALREADY_EXISTS, // reports.h5 file already exists, so action is blocked. Fixed in branch to be merged in.
    MATHOVERRIDES_SurfToVol,
    MATH_GENERATION_FAILURE,
    MATH_OVERRIDES_A_FUNCTION,
    MATH_OVERRIDES_INVALID,
    NESTED_SEDML_REPEATED_TASK, // We can do a repeated task of a normal task, but not another repeated task.
    NULL_POINTER_EXCEPTION,
    OPERATION_NOT_SUPPORTED, // VCell simply doesn't have the necessary features to run this archive.
    SBML_IMPORT_FAILURE,
    SEDML_IMPORT_FAILURE,
    SEDML_DIFF_NUMBER_OF_BIOMODELS,
    SEDML_ERRONEOUS_UNIT_SYSTEM,
    SEDML_ERROR_CONSTRUCTING_SIMCONTEXT,
    SEDML_MATH_OVERRIDE_NAMES_DIFFERENT,
    SEDML_MATH_OVERRIDE_NOT_EQUIVALENT,
    SEDML_NONSPATIAL_STOCH_HISTOGRAM,
    SEDML_NO_MODELS_IN_OMEX,
    SEDML_SIMCONTEXT_NOT_FOUND_BY_NAME,
    SEDML_SIMULATION_NOT_FOUND_BY_NAME,
    SEDML_UNSUPPORTED_ENTITY,
    SEDML_UNSUPPORTED_MODEL_REFERENCE, // Model refers to either a non-existent model (invalid SED-ML) or to another model with changes (not supported yet)
    SEDML_NON_UTC_SIMULATION_FOUND,
    SEDML_SBML_LEVEL_CHANGE, // unsupported SBML Level change within the SED-ML
    TOO_SLOW,
    UNCATEGORIZED_FAULT,
    UNITS_EXCEPTION,
    UNKNOWN_IDENTIFIER,
    SEDML_NO_SEDMLS_TO_EXECUTE,
    SEDML_PREPROCESS_FAILURE,
    UNSUPPORTED_NONSPATIAL_STOCH_HISTOGRAM,
    UNSUPPORTED_NON_INT_STOCH,
    UNSUPPORTED_NON_NUMERIC_STOCH,
    SBML_XML_NODE_FAILURE,
    SOLVER_FAILURE,
    UNSUPPORTED_DELAY_SBML,
    UNSUPPORTED_NON_CONSTANT_COMPARTMENTS,
    BIOMODEL_IMPORT_SEDML_FAILURE,
    TIMEOUT_ENCOUNTERED
}
