FROM schaff/python-copasi-jre:latest
    
RUN mkdir -p /usr/local/app/lib
WORKDIR /usr/local/app

COPY ./vcell-server/target/vcell-server-0.0.1-SNAPSHOT.jar \
     ./vcell-server/target/maven-jars/*.jar \
     ./vcell-oracle/target/vcell-oracle-0.0.1-SNAPSHOT.jar \
     ./vcell-oracle/target/maven-jars/*.jar \
     ./ojdbc6/src/ojdbc6.jar \
     ./ucp/src/ucp.jar \
     ./vcell-api/target/vcell-api-0.0.1-SNAPSHOT.jar \
     ./vcell-api/target/maven-jars/*.jar \
     ./lib/

COPY ./pythonScripts ./pythonScripts
COPY ./vcell-api/docroot ./docroot
COPY ./vcell-api/webapp ./webapp
COPY ./vcell-api/keystore_macbook.jks .

ENV softwareVersion=SOFTWARE-VERSION-NOT-SET \
	serverid=SITE \
	dburl="db-url-not-set" \
    dbdriver="db-driver-not-set" \
    dbuser="db-user-not-set" \
    jmshost_internal=activemq \
    jmsport_internal=61616 \
    jmsrestport_internal=8161 \
    jmsuser=clientUser \
    mongodb_host_internal=mongodb \
    mongodb_port_internal=27017 \
    mongodb_database=test \
    jmsblob_minsize=100000

ENV dbpswdfile=/run/secrets/dbpswd \
    jmspswdfile=/run/secrets/jmspswd \
    keystore=/run/secrets/keystorefile \
    keystorepswdfile=/run/secrets/keystorepswd

EXPOSE 8080
EXPOSE 8000

ENTRYPOINT java \
    -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n \
    -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Xms64M \
	-Dvcell.softwareVersion="${softwareVersion}" \
	-Dvcell.server.id="${serverid}" \
	-Dvcell.python.executable=/usr/bin/python \
	-Dvcell.installDir=/usr/local/app \
	-Dvcell.server.dbConnectURL="${dburl}" \
	-Dvcell.server.dbDriverName="${dbdriver}" \
	-Dvcell.server.dbUserid="${dbuser}" \
	-Dvcell.db.pswdfile="${dbpswdfile}" \
	-Dvcell.jms.host.internal="${jmshost_internal}" \
	-Dvcell.jms.port.internal="${jmsport_internal}" \
	-Dvcell.jms.restport.internal="${jmsrestport_internal}" \
	-Dvcell.jms.blobMessageUseMongo=true \
	-Dvcell.jms.blobMessageMinSize="${jmsblob_minsize}" \
	-Dvcell.jms.user="${jmsuser}" \
	-Dvcell.jms.pswdfile="${jmspswdfile}" \
	-Dvcell.mongodb.host.internal=${mongodb_host_internal} \
	-Dvcell.mongodb.port.internal=${mongodb_port_internal} \
	-Dvcell.mongodb.database=${mongodb_database} \
	-Dvcellapi.keystore.file="${keystore}" \
	-Dvcellapi.keystore.pswdfile="${keystorepswdfile}" \
	-cp "./lib/*" org.vcell.rest.VCellApiMain \
	/usr/local/app/docroot - 8080
