FROM localhost:5000/schaff/vcell-solvers:0.0.5-dev

RUN apt-get install -y openjdk-8-jre-headless

RUN mkdir -p /usr/local/app/localsolvers && ln -s /vcellbin  /usr/local/app/localsolvers/linux64
WORKDIR /usr/local/app

COPY ./vcell-server/target/vcell-server-0.0.1-SNAPSHOT.jar \
     ./vcell-server/target/maven-jars/*.jar \
     ./lib/

COPY ./nativelibs/linux64 ./nativelibs/linux64
COPY ./docker/batch/JavaPreprocessor64 \
     ./docker/batch/JavaPostprocessor64 \
     ./docker/batch/JavaSimExe64 \
     ./docker/batch/entrypoint.sh \
     /vcellscripts/

ENV PATH=/vcellscripts:$PATH \
    CLASSPATH=/usr/local/app/lib/*

ENV softwareVersion=VCell_7.0_build_99 \
	serverid=TEST \
	installdir=/usr/local/app \
	jmshost_internal=vcell-service.cam.uchc.edu \
	jmsport_internal=61619 \
	jmsrestport_internal=8164 \
    jmsuser=clientUser \
    jmspswd=dummy \
    blob_message_use_mongo=true \
    datadir_internal=/simdata \
    datadir_external=/share/apps/vcell3/users \
    htclogdir_internal=/htclogs \
    htclogdir_external=/share/apps/vcell3/htclogs \
    mongodbhost_internal=vcell-service.cam.uchc.edu \
    mongodbport_internal=27017 \
    mongodb_database=test \
    jmsblob_minsize=100000

VOLUME /simdata
VOLUME /htclogs

ENTRYPOINT [ "/vcellscripts/entrypoint.sh" ]
