FROM nimmis/java-centos:openjdk-8-jre-headless

# consider not needing miniconda - vtk dependencies are difficult
# eventually move python packages to a separate service
#RUN cd /etc/yum.repos.d/ && \
#    wget https://download.opensuse.org/repositories/home:fbergman:COPASI/CentOS_7/home:fbergman:COPASI.repo && \
#    yum -y install python-copasi && \
#    wget https://download.opensuse.org/repositories/home:fbergman:libsbml/CentOS_7/home:fbergman:libsbml.repo && \
#    yum -y install python-libsbml && \
#    wget http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/v/vtk-6.1.0-5.el7.x86_64.rpm && \
#    rpm -Uvh vtk-6.1.0-5.el7.x86_64.rpm && \
#    yum -y install vtk
#    wget http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/v/vtk-python-6.1.0-5.el7.x86_64.rpm && \
       
# install miniconda
RUN yum -y update \
    && yum -y install curl bzip2 \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local/ \
    && rm -rf /tmp/miniconda.sh \
    && conda install -y python=2 \
    && conda update -y conda \
    && conda clean --all --yes \
    && rpm -e --nodeps bzip2 \
    && yum -y autoremove \
    && yum clean all

# install 4 reqired packages into miniconda
RUN conda install --yes -q -c sbmlteam python-libsbml \
	&& conda install --yes -q -c fbergmann python-copasi \
	&& conda install --yes -q -c conda-forge thrift \
	&& conda install --yes -q -c conda-forge vtk

RUN mkdir -p /usr/local/app/lib
WORKDIR /usr/local/app

COPY ./vcell-server/target/vcell-server-0.0.1-SNAPSHOT.jar \
     ./vcell-server/target/maven-jars/*.jar \
     ./vcell-oracle/target/vcell-oracle-0.0.1-SNAPSHOT.jar \
     ./vcell-oracle/target/maven-jars/*.jar \
     ./ojdbc6/src/ojdbc6.jar \
     ./ucp/src/ucp.jar \
     ./vcell-api/target/vcell-api-0.0.1-SNAPSHOT.jar \
     ./vcell-api/target/maven-jars/*.jar \
     ./lib/

COPY ./pythonScripts ./pythonScripts
COPY ./vcell-api/docroot ./docroot
COPY ./vcell-api/webapp ./webapp
COPY ./vcell-api/keystore_macbook.jks .

ENV softwareVersion=SOFTWARE-VERSION-NOT-SET \
	serverid=SITE \
	dburl="db-url-not-set" \
    dbdriver="db-driver-not-set" \
    dbuser="db-user-not-set" \
    jmshost_internal=activemq \
    jmsport_internal=61616 \
    jmsrestport_internal=8161 \
    jmsuser=clientUser \
    mongodb_host_internal=mongodb \
    mongodb_port_internal=27017 \
    mongodb_database=test \
    jmsblob_minsize=100000

ENV dbpswdfile=/run/secrets/dbpswd \
    jmspswdfile=/run/secrets/jmspswd \
    keystore=/run/secrets/keystorefile \
    keystorepswdfile=/run/secrets/keystorepswd

EXPOSE 8080
EXPOSE 8000

ENTRYPOINT java \
    -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n \
	-Dvcell.softwareVersion="${softwareVersion}" \
	-Dvcell.server.id="${serverid}" \
	-Dvcell.python.executable=/usr/local/bin/python \
	-Dvcell.installDir=/usr/local/app \
	-Dvcell.server.dbConnectURL="${dburl}" \
	-Dvcell.server.dbDriverName="${dbdriver}" \
	-Dvcell.server.dbUserid="${dbuser}" \
	-Dvcell.db.pswdfile="${dbpswdfile}" \
	-Dvcell.jms.host.internal="${jmshost_internal}" \
	-Dvcell.jms.port.internal="${jmsport_internal}" \
	-Dvcell.jms.restport.internal="${jmsrestport_internal}" \
	-Dvcell.jms.blobMessageUseMongo=true \
	-Dvcell.jms.blobMessageMinSize="${jmsblob_minsize}" \
	-Dvcell.jms.user="${jmsuser}" \
	-Dvcell.jms.pswdfile="${jmspswdfile}" \
	-Dvcell.mongodb.host.internal=${mongodb_host_internal} \
	-Dvcell.mongodb.port.internal=${mongodb_port_internal} \
	-Dvcell.mongodb.database=${mongodb_database} \
	-Dvcellapi.keystore.file="${keystore}" \
	-Dvcellapi.keystore.pswdfile="${keystorepswdfile}" \
	-cp "./lib/*" org.vcell.rest.VCellApiMain \
	/usr/local/app/docroot - 8080
