apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: activemqsim
  name: activemqsim
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: activemqsim
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/swarm-vcellnet: "true"
        io.kompose.service: activemqsim
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: zone
                    operator: In
                    values:
                      - INTERNAL
      containers:
        - env:
            - name: ACTIVEMQ_CONFIG_AUTHENABLED
              value: "true"
            - name: ACTIVEMQ_ENABLED_SCHEDULER
              value: "true"
            - name: ACTIVEMQ_GROUPS_reads
              value: clientUser
            - name: ACTIVEMQ_GROUPS_writes
              value: clientUser
            - name: ACTIVEMQ_MAX_MEMORY
              value: "2048"
            - name: ACTIVEMQ_MIN_MEMORY
              value: "512"
            - name: ACTIVEMQ_STATIC_QUEUES
              value: workerEvent
            - name: ACTIVEMQ_STATIC_TOPICS
              value: serviceControl
            - name: ACTIVEMQ_USERS_clientUser
              value: dummy
          image: webcenter/activemq:5.14.3
          name: activemqsim
          ports:
            - containerPort: 61616
              hostPort: 61619
              protocol: TCP
            - containerPort: 8161
              hostPort: 8164
              protocol: TCP
          resources:
            limits:
              memory: "2097152e3"
            requests:
              memory: "1048576e3"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: activemqsim
  name: activemqsim
spec:
  ports:
    - name: "61619"
      port: 61619
      targetPort: 61616
    - name: "8164"
      port: 8164
      targetPort: 8161
  selector:
    io.kompose.service: activemqsim
