/*
 * Copyright (C) 1999-2011 University of Connecticut Health Center
 *
 * Licensed under the MIT License (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *  http://www.opensource.org/licenses/mit-license.php
 */

package cbit.vcell.server;

import cbit.plot.PlotData;
import cbit.rmi.event.ExportEvent;
import cbit.vcell.export.server.ExportSpecs;
import cbit.vcell.field.io.FieldData;
import cbit.vcell.field.io.FieldDataShape;
import cbit.vcell.field.io.FieldDataSpec;
import cbit.vcell.message.server.bootstrap.client.RemoteProxyException;
import cbit.vcell.simdata.*;
import cbit.vcell.solver.AnnotatedFunction;
import cbit.vcell.solvers.CartesianMesh;
import org.vcell.solver.nfsim.NFSimMolecularConfigurations;
import org.vcell.util.DataAccessException;
import org.vcell.util.document.ExternalDataIdentifier;
import org.vcell.util.document.KeyValue;
import org.vcell.util.document.VCDataIdentifier;
import org.vcell.vis.io.VtuFileContainer;
import org.vcell.vis.io.VtuVarInfo;

/**
 * This interface was generated by a SmartGuide.
 * 
 */
public interface DataSetController {

 public ExternalDataIdentifier analyzeAndCreateFieldData(FieldDataSpec fieldDataSpec) throws DataAccessException;

 public ExternalDataIdentifier saveFieldData(FieldData fieldData) throws DataAccessException;

 public void deleteFieldData(KeyValue fieldDataKey);

 public FieldDataShape getFieldDataShape(KeyValue fieldDataKey) throws DataAccessException;

/**
 * This method was created by a SmartGuide.
 * @exception RemoteProxyException The exception description.
 */
public DataIdentifier[] getDataIdentifiers(OutputContext outputContext, VCDataIdentifier vcdataID) throws RemoteProxyException, DataAccessException;
/**
 * This method was created by a SmartGuide.
 * @exception RemoteProxyException The exception description.
 */
public double[] getDataSetTimes(VCDataIdentifier vcdataID) throws RemoteProxyException, DataAccessException;

public double[] getVtuTimes(VCDataIdentifier vcdataID) throws RemoteProxyException, DataAccessException;

AnnotatedFunction[] getFunctions(OutputContext outputContext,VCDataIdentifier vcdataID) throws DataAccessException, RemoteProxyException;

public PlotData getLineScan(OutputContext outputContext, VCDataIdentifier vcdataID, String variable, double time, SpatialSelection spatialSelection) throws RemoteProxyException, DataAccessException;

public VtuFileContainer getEmptyVtuMeshFiles(VCDataIdentifier vcdataID, int timeIndex) throws RemoteProxyException, DataAccessException;


public double[] getVtuMeshData(OutputContext outputContext, VCDataIdentifier vcdataID, VtuVarInfo var, double time) throws RemoteProxyException, DataAccessException;

public NFSimMolecularConfigurations getNFSimMolecularConfigurations(VCDataIdentifier vcdataID) throws RemoteProxyException, DataAccessException;

CartesianMesh getMesh(VCDataIdentifier vcdataID) throws RemoteProxyException, DataAccessException;

cbit.vcell.solver.ode.ODESimData getODEData(VCDataIdentifier vcdataID) throws DataAccessException, RemoteProxyException;

/**
 *
 * getLangevinBatchResultSet
 */
 LangevinBatchResultSet getLangevinBatchResultSet(VCDataIdentifier vcdataID) throws DataAccessException, RemoteProxyException;

/**
 * getLangevinTrajectory - per-particle SpringSaLaD trajectory ("viewer" file) for the 3D
 * renderer. Default returns null so implementors that do not serve sim data are unaffected;
 * the real data paths (local + RPC) override it.
 */
 default cbit.vcell.simdata.SpringSaladTrajectory getLangevinTrajectory(VCDataIdentifier vcdataID) throws DataAccessException, RemoteProxyException {
 	return null;
 }

/**
 * getFenicsBundleFile - one file of a FEniCSx results bundle, {@code SimID_<key>_<job>_.fenics/<relativePath>}
 * (docs/plan-fenics.md, V5), so a cluster run's results can be viewed from the desktop. Returns null when
 * the file does not exist (an unwritten chunk of a running simulation). Default returns null so
 * implementors that do not serve sim data are unaffected; the real data paths (local + RPC) override it.
 */
 default byte[] getFenicsBundleFile(VCDataIdentifier vcdataID, String relativePath) throws DataAccessException, RemoteProxyException {
 	return null;
 }

/**
 * getFenicsBundleFiles - several files of a FEniCSx results bundle in one call (a kymograph's rows),
 * each null if it does not exist. The answer may be a PREFIX of the paths asked for: the data server
 * stops adding files once the reply is large enough, and the caller asks again for the rest. Default
 * reads them one by one through {@link #getFenicsBundleFile}.
 */
/**
 * getFenicsBundleSamples - some values of some arrays of a FEniCSx results bundle, read and decoded where the
 * bundle is (a kymograph's or probe's mesh vertices at every row, rather than the whole rows): for each of
 * {@code arrayPaths} (bundle-relative zarr arrays sharing one row length -- one domain of one segment), at
 * each of {@code rows} (rows of those arrays), the values at {@code indices} (strictly increasing). The answer
 * may cover only a PREFIX of the rows: it stops at a size budget and the caller asks again for the rest. See
 * {@link org.vcell.solver.fenics.FenicsBundle#gather}. Default returns null: not served here, read whole rows.
 */
 default org.vcell.solver.fenics.FenicsSamples getFenicsBundleSamples(VCDataIdentifier vcdataID, String[] arrayPaths, int[] indices, int[] rows) throws DataAccessException, RemoteProxyException {
 	return null;
 }

/**
 * getFenicsBundleLocatedSamples - lab-frame {@code points} (x,y,z each) located in a MOVING (ALE) segment's mesh at
 * each of {@code rows} (rows of that segment's arrays), where the bundle is: per row the cell each point fell in
 * (snapped onto a membrane mesh when {@code snap}), those cells' vertices with their positions in that row, and
 * the values of {@code arrayPaths} there, instead of every row's whole positions and values. {@code meshPath} is
 * the segment's VTU mesh, {@code coordsPath} its point positions. The answer may cover only a PREFIX of the rows;
 * the caller asks again for the rest. See {@link org.vcell.solver.fenics.FenicsBundle#locate}. Default returns
 * null: not served here, read whole rows.
 */
 default org.vcell.solver.fenics.FenicsLocatedSamples getFenicsBundleLocatedSamples(VCDataIdentifier vcdataID, String meshPath, String coordsPath, String[] arrayPaths, double[] points, boolean snap, int[] rows) throws DataAccessException, RemoteProxyException {
 	return null;
 }

 default byte[][] getFenicsBundleFiles(VCDataIdentifier vcdataID, String[] relativePaths) throws DataAccessException, RemoteProxyException {
 	byte[][] files = new byte[relativePaths.length][];
 	for (int i = 0; i < files.length; i++) {
 		files[i] = getFenicsBundleFile(vcdataID, relativePaths[i]);
 	}
 	return files;
 }

 /**
 * This method was created in VisualAge.
 * @return ParticleData
 * @param time double
 * @exception org.vcell.util.DataAccessException The exception description.
 * @exception RemoteProxyException The exception description.
 */
cbit.vcell.simdata.ParticleDataBlock getParticleDataBlock(VCDataIdentifier vcdataID, double time) throws DataAccessException, RemoteProxyException;
/**
 * This method was created in VisualAge.
 * @return boolean
 */

public DataSetMetadata getDataSetMetadata(VCDataIdentifier vcdataID) throws DataAccessException, RemoteProxyException;

public DataSetTimeSeries getDataSetTimeSeries(VCDataIdentifier vcdataID, String[] variableNames) throws DataAccessException, RemoteProxyException;

public DataOperationResults doDataOperation(DataOperation dataOperation) throws DataAccessException, RemoteProxyException;


public boolean getParticleDataExists(VCDataIdentifier vcdataID) throws DataAccessException, RemoteProxyException;
/**
 * This method was created by a SmartGuide.
 * @return java.lang.String
 * @exception RemoteProxyException The exception description.
 */
public cbit.vcell.simdata.SimDataBlock getSimDataBlock(OutputContext outputContext, VCDataIdentifier vcdataID, String varName, double time) throws RemoteProxyException, DataAccessException;

public org.vcell.util.document.TimeSeriesJobResults getTimeSeriesValues(OutputContext outputContext, VCDataIdentifier vcdataID, org.vcell.util.document.TimeSeriesJobSpec timeSeriesJobSpec) throws RemoteProxyException, DataAccessException;
/**
 * Insert the method's description here.
 * Creation date: (10/22/2001 2:53:44 PM)
 * @return cbit.rmi.event.ExportEvent
 * @param exportSpecs cbit.vcell.export.server.ExportSpecs
 * @exception org.vcell.util.DataAccessException The exception description.
 * @exception RemoteProxyException The exception description.
 */
ExportEvent makeRemoteFile(OutputContext outputContext,ExportSpecs exportSpecs) throws DataAccessException, RemoteProxyException;


public VtuVarInfo[] getVtuVarInfos(OutputContext outputContext,	VCDataIdentifier vcDataIdentifier) throws DataAccessException, RemoteProxyException;

}
