apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: data
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/swarm-vcellnet: "true"
        io.kompose.service: data
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: zone
                    operator: In
                    values:
                      - INTERNAL
      containers:
        - env:
            - name: dbdriver
              value: oracle.jdbc.driver.OracleDriver
            - name: dburl
              value: jdbc:oracle:thin:@vcell-oracle.cam.uchc.edu:1521/ORCLPDB1
            - name: dbuser
              value: vcell
            - name: export_baseurl
              value: http://vcell.org/export/
            - name: jmshost_int_internal
              value: activemqint
            - name: jmsport_int_internal
              value: "61616"
            - name: jmsuser
              value: clientUser
            - name: mongodb_database
              value: test
            - name: mongodb_host_internal
              value: mongodb
            - name: mongodb_port_internal
              value: "27017"
            - name: s3ProxyPortExternal
              value: "8089"
            - name: s3export_baseURL
              value: https://localhost
            - name: serverid
              value: TEST
            - name: servertype
              value: CombinedData
            - name: simdataCacheSize
              value: "10000000"
            - name: softwareVersion
              value: Test_Version_7.5.0_build_1234
            - name: webDataPort
              value: "55556"
          image: ghcr.io/virtualcell/vcell-data:dev
          name: data
          ports:
            - containerPort: 8000
              hostPort: 5002
              protocol: TCP
          resources:
            limits:
              memory: "3145728e3"
            requests:
              memory: "3145728e3"
          volumeMounts:
            - mountPath: /run/secrets/dbpswd
              name: dbpswd
            - mountPath: /run/secrets/jmspswd
              name: jmspswd
            - mountPath: /run/secrets/keystorefile
              name: keystorefile
            - mountPath: /run/secrets/keystorepswd
              name: keystorepswd
            - mountPath: /simdata
              name: data-claim0
            - mountPath: /n5DataDir
              name: data-claim1
            - mountPath: /share/apps/vcell12/users
              name: data-claim2
            - mountPath: /simdata_secondary
              name: data-claim3
            - mountPath: /exportdir
              name: data-claim4
      restartPolicy: Always
      volumes:
        - name: dbpswd
          secret:
            items:
              - key: dbpswd
                path: dbpswd
            secretName: dbpswd
        - name: jmspswd
          secret:
            items:
              - key: jmspswd
                path: jmspswd
            secretName: jmspswd
        - name: keystorefile
          secret:
            items:
              - key: keystorefile
                path: keystorefile
            secretName: keystorefile
        - name: keystorepswd
          secret:
            items:
              - key: keystorepswd
                path: keystorepswd
            secretName: keystorepswd
        - name: data-claim0
          persistentVolumeClaim:
            claimName: data-claim0
        - name: data-claim1
          persistentVolumeClaim:
            claimName: data-claim1
        - name: data-claim2
          persistentVolumeClaim:
            claimName: data-claim2
        - name: data-claim3
          persistentVolumeClaim:
            claimName: data-claim3
        - name: data-claim4
          persistentVolumeClaim:
            claimName: data-claim4
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../swarm/docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: data
  name: data
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 8000
  selector:
    io.kompose.service: data
