export * from './admin-resource.service';
import { AdminResourceService } from './admin-resource.service';
export * from './admin-resource.serviceInterface';
export * from './bio-model-resource.service';
import { BioModelResourceService } from './bio-model-resource.service';
export * from './bio-model-resource.serviceInterface';
export * from './field-data-resource.service';
import { FieldDataResourceService } from './field-data-resource.service';
export * from './field-data-resource.serviceInterface';
export * from './geometry-resource.service';
import { GeometryResourceService } from './geometry-resource.service';
export * from './geometry-resource.serviceInterface';
export * from './hello-world.service';
import { HelloWorldService } from './hello-world.service';
export * from './hello-world.serviceInterface';
export * from './math-model-resource.service';
import { MathModelResourceService } from './math-model-resource.service';
export * from './math-model-resource.serviceInterface';
export * from './publication-resource.service';
import { PublicationResourceService } from './publication-resource.service';
export * from './publication-resource.serviceInterface';
export * from './simulation-resource.service';
import { SimulationResourceService } from './simulation-resource.service';
export * from './simulation-resource.serviceInterface';
export * from './solver-resource.service';
import { SolverResourceService } from './solver-resource.service';
export * from './solver-resource.serviceInterface';
export * from './users-resource.service';
import { UsersResourceService } from './users-resource.service';
export * from './users-resource.serviceInterface';
export * from './vc-image-resource.service';
import { VCImageResourceService } from './vc-image-resource.service';
export * from './vc-image-resource.serviceInterface';
export const APIS = [AdminResourceService, BioModelResourceService, FieldDataResourceService, GeometryResourceService, HelloWorldService, MathModelResourceService, PublicationResourceService, SimulationResourceService, SolverResourceService, UsersResourceService, VCImageResourceService];
