export * from './admin-resource.service';
import { AdminResourceService } from './admin-resource.service';
export * from './admin-resource.serviceInterface';
export * from './bio-model-resource.service';
import { BioModelResourceService } from './bio-model-resource.service';
export * from './bio-model-resource.serviceInterface';
export * from './hello-world.service';
import { HelloWorldService } from './hello-world.service';
export * from './hello-world.serviceInterface';
export * from './publication-resource.service';
import { PublicationResourceService } from './publication-resource.service';
export * from './publication-resource.serviceInterface';
export * from './simulation-resource.service';
import { SimulationResourceService } from './simulation-resource.service';
export * from './simulation-resource.serviceInterface';
export * from './users-resource.service';
import { UsersResourceService } from './users-resource.service';
export * from './users-resource.serviceInterface';
export const APIS = [AdminResourceService, BioModelResourceService, HelloWorldService, PublicationResourceService, SimulationResourceService, UsersResourceService];
