/**
 * VCell API
 *
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HelloWorldMessage } from '../model/models';
import { VCellHTTPError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HelloWorldServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get hello world message.
     * 
     * @endpoint get /api/v1/helloworld
     */
    getHelloWorld(extraHttpRequestParams?: any): Observable<HelloWorldMessage>;

}
