apiVersion: v1
kind: PersistentVolume
metadata:
  name: cfs09-vcell-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /vcell
    server: cfs09.cam.uchc.edu
#  mountOptions:
#    - nfsvers=4.2
