apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongodb-pvc
    labels:
        app: mongodb
spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 5Gi
