apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # corresponds to the NFS mount of cfs12:/vcell to /share/apps/vcell12 on swarm nodes
  name: nfs-archive-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1000Gi
  volumeName: cfs12-vcell-pv