/*
 * VCell API
 * VCell API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.vcell.restclient.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;

import com.fasterxml.jackson.annotation.*;

import java.time.LocalDate;
import java.util.Arrays;
import org.vcell.restclient.model.SimulationQueueID;


/**
 * SimulationQueueEntryStatus
 */
@JsonPropertyOrder({
  SimulationQueueEntryStatus.JSON_PROPERTY_FIELD_QUEUE_PRIORITY,
  SimulationQueueEntryStatus.JSON_PROPERTY_FIELD_QUEUE_DATE,
  SimulationQueueEntryStatus.JSON_PROPERTY_FIELD_QUEUE_I_D,
  SimulationQueueEntryStatus.JSON_PROPERTY_QUEUE_DATE,
  SimulationQueueEntryStatus.JSON_PROPERTY_QUEUE_I_D,
  SimulationQueueEntryStatus.JSON_PROPERTY_QUEUE_PRIORITY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SimulationQueueEntryStatus {
  public static final String JSON_PROPERTY_FIELD_QUEUE_PRIORITY = "fieldQueuePriority";
  private Integer fieldQueuePriority;

  public static final String JSON_PROPERTY_FIELD_QUEUE_DATE = "fieldQueueDate";
  private LocalDate fieldQueueDate;

  public static final String JSON_PROPERTY_FIELD_QUEUE_I_D = "fieldQueueID";
  private SimulationQueueID fieldQueueID;

  public static final String JSON_PROPERTY_QUEUE_DATE = "queueDate";
  private LocalDate queueDate;

  public static final String JSON_PROPERTY_QUEUE_I_D = "queueID";
  private SimulationQueueID queueID;

  public static final String JSON_PROPERTY_QUEUE_PRIORITY = "queuePriority";
  private Integer queuePriority;

  public SimulationQueueEntryStatus() { 
  }

  public SimulationQueueEntryStatus fieldQueuePriority(Integer fieldQueuePriority) {
    this.fieldQueuePriority = fieldQueuePriority;
    return this;
  }

   /**
   * Get fieldQueuePriority
   * @return fieldQueuePriority
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIELD_QUEUE_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFieldQueuePriority() {
    return fieldQueuePriority;
  }


  @JsonProperty(JSON_PROPERTY_FIELD_QUEUE_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFieldQueuePriority(Integer fieldQueuePriority) {
    this.fieldQueuePriority = fieldQueuePriority;
  }


  public SimulationQueueEntryStatus fieldQueueDate(LocalDate fieldQueueDate) {
    this.fieldQueueDate = fieldQueueDate;
    return this;
  }

   /**
   * Get fieldQueueDate
   * @return fieldQueueDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIELD_QUEUE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getFieldQueueDate() {
    return fieldQueueDate;
  }


  @JsonProperty(JSON_PROPERTY_FIELD_QUEUE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFieldQueueDate(LocalDate fieldQueueDate) {
    this.fieldQueueDate = fieldQueueDate;
  }


  public SimulationQueueEntryStatus fieldQueueID(SimulationQueueID fieldQueueID) {
    this.fieldQueueID = fieldQueueID;
    return this;
  }

   /**
   * Get fieldQueueID
   * @return fieldQueueID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIELD_QUEUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SimulationQueueID getFieldQueueID() {
    return fieldQueueID;
  }


  @JsonProperty(JSON_PROPERTY_FIELD_QUEUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFieldQueueID(SimulationQueueID fieldQueueID) {
    this.fieldQueueID = fieldQueueID;
  }


  public SimulationQueueEntryStatus queueDate(LocalDate queueDate) {
    this.queueDate = queueDate;
    return this;
  }

   /**
   * Get queueDate
   * @return queueDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUEUE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getQueueDate() {
    return queueDate;
  }


  @JsonProperty(JSON_PROPERTY_QUEUE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueueDate(LocalDate queueDate) {
    this.queueDate = queueDate;
  }


  public SimulationQueueEntryStatus queueID(SimulationQueueID queueID) {
    this.queueID = queueID;
    return this;
  }

   /**
   * Get queueID
   * @return queueID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUEUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SimulationQueueID getQueueID() {
    return queueID;
  }


  @JsonProperty(JSON_PROPERTY_QUEUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueueID(SimulationQueueID queueID) {
    this.queueID = queueID;
  }


  public SimulationQueueEntryStatus queuePriority(Integer queuePriority) {
    this.queuePriority = queuePriority;
    return this;
  }

   /**
   * Get queuePriority
   * @return queuePriority
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUEUE_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQueuePriority() {
    return queuePriority;
  }


  @JsonProperty(JSON_PROPERTY_QUEUE_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueuePriority(Integer queuePriority) {
    this.queuePriority = queuePriority;
  }


  /**
   * Return true if this SimulationQueueEntryStatus object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimulationQueueEntryStatus simulationQueueEntryStatus = (SimulationQueueEntryStatus) o;
    return Objects.equals(this.fieldQueuePriority, simulationQueueEntryStatus.fieldQueuePriority) &&
        Objects.equals(this.fieldQueueDate, simulationQueueEntryStatus.fieldQueueDate) &&
        Objects.equals(this.fieldQueueID, simulationQueueEntryStatus.fieldQueueID) &&
        Objects.equals(this.queueDate, simulationQueueEntryStatus.queueDate) &&
        Objects.equals(this.queueID, simulationQueueEntryStatus.queueID) &&
        Objects.equals(this.queuePriority, simulationQueueEntryStatus.queuePriority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldQueuePriority, fieldQueueDate, fieldQueueID, queueDate, queueID, queuePriority);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimulationQueueEntryStatus {\n");
    sb.append("    fieldQueuePriority: ").append(toIndentedString(fieldQueuePriority)).append("\n");
    sb.append("    fieldQueueDate: ").append(toIndentedString(fieldQueueDate)).append("\n");
    sb.append("    fieldQueueID: ").append(toIndentedString(fieldQueueID)).append("\n");
    sb.append("    queueDate: ").append(toIndentedString(queueDate)).append("\n");
    sb.append("    queueID: ").append(toIndentedString(queueID)).append("\n");
    sb.append("    queuePriority: ").append(toIndentedString(queuePriority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `fieldQueuePriority` to the URL query string
    if (getFieldQueuePriority() != null) {
      joiner.add(String.format("%sfieldQueuePriority%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFieldQueuePriority()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `fieldQueueDate` to the URL query string
    if (getFieldQueueDate() != null) {
      joiner.add(String.format("%sfieldQueueDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFieldQueueDate()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `fieldQueueID` to the URL query string
    if (getFieldQueueID() != null) {
      joiner.add(String.format("%sfieldQueueID%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFieldQueueID()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `queueDate` to the URL query string
    if (getQueueDate() != null) {
      joiner.add(String.format("%squeueDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getQueueDate()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `queueID` to the URL query string
    if (getQueueID() != null) {
      joiner.add(String.format("%squeueID%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getQueueID()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `queuePriority` to the URL query string
    if (getQueuePriority() != null) {
      joiner.add(String.format("%squeuePriority%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getQueuePriority()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

