/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionParserConstants.java */
package cbit.vcell.parser;

public interface ExpressionParserConstants {

  int EOF = 0;
  int RELATIONAL_OPERATOR = 5;
  int LT = 6;
  int GT = 7;
  int LE = 8;
  int GE = 9;
  int EQ = 10;
  int NE = 11;
  int AND = 12;
  int OR = 13;
  int NOT = 14;
  int POWER = 15;
  int ADD = 16;
  int SUB = 17;
  int MULT = 18;
  int DIV = 19;
  int FLOATING_POINT_LITERAL = 20;
  int EXPONENT = 21;
  int INTEGER_LITERAL = 22;
  int IDENTIFIER = 23;
  int ID = 24;
  int LETTER = 25;
  int DIGIT = 26;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<RELATIONAL_OPERATOR>",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "\"^\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
