/*
 * VCell API
 * VCell API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: vcell_support@uchc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.vcell.restclient.api;

import org.vcell.restclient.ApiClient;
import org.vcell.restclient.ApiException;
import org.vcell.restclient.ApiResponse;
import org.vcell.restclient.Pair;

import org.vcell.restclient.model.BioModel;
import org.vcell.restclient.model.BioModelContext;
import org.vcell.restclient.model.SaveBioModel;
import org.vcell.restclient.model.VCellHTTPError;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BioModelResourceApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public BioModelResourceApi() {
    this(new ApiClient());
  }

  public BioModelResourceApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Delete the BioModel from VCell&#39;s database.
   * 
   * @param bioModelID  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteBioModel(String bioModelID) throws ApiException {
    deleteBioModelWithHttpInfo(bioModelID);
  }

  /**
   * Delete the BioModel from VCell&#39;s database.
   * 
   * @param bioModelID  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteBioModelWithHttpInfo(String bioModelID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteBioModelRequestBuilder(bioModelID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteBioModel", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteBioModelRequestBuilder(String bioModelID) throws ApiException {
    // verify the required parameter 'bioModelID' is set
    if (bioModelID == null) {
      throw new ApiException(400, "Missing the required parameter 'bioModelID' when calling deleteBioModel");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/bioModel/{bioModelID}"
        .replace("{bioModelID}", ApiClient.urlEncode(bioModelID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * All of the BioModel contexts owned by the requester. If provided with a boolean of &#39;true&#39;, all public BioModel contexts VCell has will be given.
   * 
   * @param allVCellContexts  (optional)
   * @return List&lt;BioModelContext&gt;
   * @throws ApiException if fails to make API call
   */
  public List<BioModelContext> getAllBioModelContexts(Boolean allVCellContexts) throws ApiException {
    ApiResponse<List<BioModelContext>> localVarResponse = getAllBioModelContextsWithHttpInfo(allVCellContexts);
    return localVarResponse.getData();
  }

  /**
   * All of the BioModel contexts owned by the requester. If provided with a boolean of &#39;true&#39;, all public BioModel contexts VCell has will be given.
   * 
   * @param allVCellContexts  (optional)
   * @return ApiResponse&lt;List&lt;BioModelContext&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<BioModelContext>> getAllBioModelContextsWithHttpInfo(Boolean allVCellContexts) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getAllBioModelContextsRequestBuilder(allVCellContexts);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getAllBioModelContexts", localVarResponse);
        }
        return new ApiResponse<List<BioModelContext>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<BioModelContext>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getAllBioModelContextsRequestBuilder(Boolean allVCellContexts) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/bioModel/contexts";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "allVCellContexts";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("allVCellContexts", allVCellContexts));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Get BioModel.
   * 
   * @param bioModelID  (required)
   * @return BioModel
   * @throws ApiException if fails to make API call
   */
  public BioModel getBioModel(String bioModelID) throws ApiException {
    ApiResponse<BioModel> localVarResponse = getBioModelWithHttpInfo(bioModelID);
    return localVarResponse.getData();
  }

  /**
   * Get BioModel.
   * 
   * @param bioModelID  (required)
   * @return ApiResponse&lt;BioModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<BioModel> getBioModelWithHttpInfo(String bioModelID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getBioModelRequestBuilder(bioModelID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getBioModel", localVarResponse);
        }
        return new ApiResponse<BioModel>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<BioModel>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getBioModelRequestBuilder(String bioModelID) throws ApiException {
    // verify the required parameter 'bioModelID' is set
    if (bioModelID == null) {
      throw new ApiException(400, "Missing the required parameter 'bioModelID' when calling getBioModel");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/bioModel/{bioModelID}"
        .replace("{bioModelID}", ApiClient.urlEncode(bioModelID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * All of the text based information about a BioModel (summary, version, publication status, etc...), but not the actual BioModel itself.
   * 
   * @param bioModelID  (required)
   * @return BioModelContext
   * @throws ApiException if fails to make API call
   */
  public BioModelContext getBioModelContext(String bioModelID) throws ApiException {
    ApiResponse<BioModelContext> localVarResponse = getBioModelContextWithHttpInfo(bioModelID);
    return localVarResponse.getData();
  }

  /**
   * All of the text based information about a BioModel (summary, version, publication status, etc...), but not the actual BioModel itself.
   * 
   * @param bioModelID  (required)
   * @return ApiResponse&lt;BioModelContext&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<BioModelContext> getBioModelContextWithHttpInfo(String bioModelID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getBioModelContextRequestBuilder(bioModelID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getBioModelContext", localVarResponse);
        }
        return new ApiResponse<BioModelContext>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<BioModelContext>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getBioModelContextRequestBuilder(String bioModelID) throws ApiException {
    // verify the required parameter 'bioModelID' is set
    if (bioModelID == null) {
      throw new ApiException(400, "Missing the required parameter 'bioModelID' when calling getBioModelContext");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/bioModel/{bioModelID}/context"
        .replace("{bioModelID}", ApiClient.urlEncode(bioModelID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Get the BioModel in VCML format.
   * 
   * @param bioModelID  (required)
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String getBioModelVCML(String bioModelID) throws ApiException {
    ApiResponse<String> localVarResponse = getBioModelVCMLWithHttpInfo(bioModelID);
    return localVarResponse.getData();
  }

  /**
   * Get the BioModel in VCML format.
   * 
   * @param bioModelID  (required)
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> getBioModelVCMLWithHttpInfo(String bioModelID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getBioModelVCMLRequestBuilder(bioModelID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getBioModelVCML", localVarResponse);
        }
        return new ApiResponse<String>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<String>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getBioModelVCMLRequestBuilder(String bioModelID) throws ApiException {
    // verify the required parameter 'bioModelID' is set
    if (bioModelID == null) {
      throw new ApiException(400, "Missing the required parameter 'bioModelID' when calling getBioModelVCML");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/bioModel/{bioModelID}/vcml_download"
        .replace("{bioModelID}", ApiClient.urlEncode(bioModelID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "text/xml, application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Save&#39;s the given BioModel. Optional parameters of name and simulations to update due to math changes. Returns saved BioModel as VCML.
   * 
   * @param saveBioModel  (optional)
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String saveBioModel(SaveBioModel saveBioModel) throws ApiException {
    ApiResponse<String> localVarResponse = saveBioModelWithHttpInfo(saveBioModel);
    return localVarResponse.getData();
  }

  /**
   * Save&#39;s the given BioModel. Optional parameters of name and simulations to update due to math changes. Returns saved BioModel as VCML.
   * 
   * @param saveBioModel  (optional)
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> saveBioModelWithHttpInfo(SaveBioModel saveBioModel) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = saveBioModelRequestBuilder(saveBioModel);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("saveBioModel", localVarResponse);
        }
        return new ApiResponse<String>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<String>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder saveBioModelRequestBuilder(SaveBioModel saveBioModel) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/bioModel/save";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/xml, application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(saveBioModel);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
}
