# coding: utf-8

"""
    VCell API

    VCell API

    The version of the OpenAPI document: 1.0.1
    Contact: vcell_support@uchc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from importlib import import_module
from pydantic import ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from vcell_client.models.coordinate import Coordinate
from vcell_client.models.curve import Curve
from typing import Optional, Set
from typing_extensions import Self

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from vcell_client.models.sampled_curve import SampledCurve
    from vcell_client.models.spline import Spline

class ControlPointCurve(Curve):
    """
    ControlPointCurve
    """ # noqa: E501
    type: StrictStr
    control_points: Optional[List[Coordinate]] = Field(default=None, alias="controlPoints")
    control_point_count: Optional[StrictInt] = Field(default=None, alias="controlPointCount")
    control_points_vector: Optional[List[Coordinate]] = Field(default=None, alias="controlPointsVector")
    max_control_points: Optional[StrictInt] = Field(default=None, alias="maxControlPoints")
    min_control_points: Optional[StrictInt] = Field(default=None, alias="minControlPoints")
    control_point_addable: Optional[StrictBool] = Field(default=None, alias="controlPointAddable")
    valid: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["bClosed", "description", "type", "beginningCoordinate", "defaultNumSamples", "endingCoordinate", "numSamplePoints", "segmentCount", "spatialLength", "closed", "valid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = 'type'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'SampledCurve': 'SampledCurve','Spline': 'Spline'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Union[SampledCurve, Spline]]:
        """Create an instance of ControlPointCurve from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of beginning_coordinate
        if self.beginning_coordinate:
            _dict['beginningCoordinate'] = self.beginning_coordinate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ending_coordinate
        if self.ending_coordinate:
            _dict['endingCoordinate'] = self.ending_coordinate.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Optional[Union[SampledCurve, Spline]]:
        """Create an instance of ControlPointCurve from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type ==  'SampledCurve':
            return import_module("vcell_client.models.sampled_curve").SampledCurve.from_dict(obj)
        if object_type ==  'Spline':
            return import_module("vcell_client.models.spline").Spline.from_dict(obj)

        raise ValueError("ControlPointCurve failed to lookup discriminator value from " +
                            json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                            ", mapping: " + json.dumps(cls.__discriminator_value_class_map))


