# coding: utf-8

"""
    VCell API

    VCell API

    The version of the OpenAPI document: 1.0.1
    Contact: vcell_support@uchc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ExportFormat(str, Enum):
    """
    ExportFormat
    """

    """
    allowed enum values
    """
    CSV = 'CSV'
    HDF5 = 'HDF5'
    QUICKTIME = 'QUICKTIME'
    GIF = 'GIF'
    ANIMATED_GIF = 'ANIMATED_GIF'
    FORMAT_JPEG = 'FORMAT_JPEG'
    NRRD = 'NRRD'
    UCD = 'UCD'
    VTK_UNSTRUCT = 'VTK_UNSTRUCT'
    VTK_IMAGE = 'VTK_IMAGE'
    PLY = 'PLY'
    N5 = 'N5'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExportFormat from a JSON string"""
        return cls(json.loads(json_str))


