//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 03:55:47 PM EST 
//


package neuroml.network;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for SynapseDirection.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SynapseDirection">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="pre"/>
 *     &lt;enumeration value="post"/>
 *     &lt;enumeration value="preAndOrPost"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum SynapseDirection {

    @XmlEnumValue("pre")
    PRE("pre"),
    @XmlEnumValue("post")
    POST("post"),
    @XmlEnumValue("preAndOrPost")
    PRE_AND_OR_POST("preAndOrPost");
    private final String value;

    SynapseDirection(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SynapseDirection fromValue(String v) {
        for (SynapseDirection c: SynapseDirection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
