apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - minikube.local
  commonName: minikube.local
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
    kind: ClusterIssuer