# ingress for api
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  labels:
    app: api
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
    rules:
    - host: minikube.local
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
                name: api
                port:
                  number: 8083
