apiVersion: v1
kind: PersistentVolume
metadata:
  name: cfs07-vcell-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /ifs/vcell
    server: cfs07.cam.uchc.edu
#  mountOptions:
#    - nfsvers=4.2
