apiVersion: v1
kind: PersistentVolume
metadata:
  name: cfs05-vcellroot-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /vcellroot
    server: cfs05.cam.uchc.edu
#  mountOptions:
#    - nfsvers=4.2
