apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongodbdata
spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: standard
    resources:
        requests:
            storage: 100Mi
