---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jms-secret
  namespace: devjim
spec:
  encryptedData:
    password: AgCB2NCYNi6Op7Fd5ReEjOn07etLUBJ2ZUUwLPgvqTw02iVvYLol4bdexAMu/9WjwS7PqvSXPe/o8cFY9RU/eOPi7lBU9rGBKFRV4u5b76NW2jgCvwvfMzSqGLuja0kOI+VqJ0rnsA1OL2SDF7nyUfvAWaZ6Xfh+ybw8oroNkwA0tya3R0wYR/D/dBJvcFR0wFzE+ijb4qbRMbqcRULP8dNaT5E0mlg7/OPNWag+/Dl/Ay3TnFhB6M3yjQg2c2UE+CJ78yxNVK+/nAMSaIZONXKqk7P261EgsYvKSnFWAkv6b5cW+pxPjAe/W4vrlA8yQ7SHjwcAJBxZzWvdKe+HYxRsO3urGxJZ7z7q5o+zXiVdltg+nZ7AAzhadLq0crOMO0/rbSe6S3uPKS+YllI9ergsscDVbI3hMr44JHKBQ15yCmwbOEL0qOxErs+7b9RQR24TFstXtWffiEh+OUAvQVh8FEVAiMWYp7CxANCwMtVWuId1ARlRX2lxdZ0lgMzmAr2obxQNsjqrIqa8Q1PaQuIKQlmztWdKo0k7+ohXDkKKnaNqT38bQF8HD3T56RG9mtQHOsfmL1EWBVmj4wPnygoL5DXOgohDcI68wvXv5sEks1zg1hRCCEi1vSz8hQKlBMsJ1blqjFJwanj7jNoSdoQeZbjRHjI6mq/NadO1Hj6LiWkTsWMX8aUegB4Kx+y8GRXTsWx3AQ==
  template:
    metadata:
      creationTimestamp: null
      name: jms-secret
      namespace: devjim
