---
openapi: 3.0.3
info:
  title: VCell API
  description: VCell API
  termsOfService: Your terms of service here
  contact:
    name: VCell API Support
    url: http://exampleurl.com/contact
    email: vcell_support@uchc.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  version: 1.0.1
servers:
- url: https://vcellapi-test.cam.uchc.edu
paths:
  /api/v1/admin/usage:
    get:
      tags:
      - Admin Resource
      summary: Get usage summary
      operationId: getUsage
      responses:
        "200":
          description: The PDF report
          content:
            application/pdf:
              schema:
                format: binary
                type: string
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - openId:
        - admin
  /api/v1/bioModel/upload_bioModel:
    post:
      tags:
      - Bio Model Resource
      summary: Upload the BioModel to VCell database. Returns BioModel ID.
      operationId: uploadBioModel
      requestBody:
        content:
          text/xml:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/v1/bioModel/{bioModelID}:
    get:
      tags:
      - Bio Model Resource
      summary: Get BioModel information in JSON format by ID.
      operationId: getBiomodelById
      parameters:
      - name: bioModelID
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BioModel'
    delete:
      tags:
      - Bio Model Resource
      summary: Delete the BioModel from VCell's database.
      operationId: deleteBioModel
      parameters:
      - name: bioModelID
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
  /api/v1/helloworld:
    get:
      tags:
      - Hello World
      summary: Get hello world message.
      operationId: getHelloWorld
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldMessage'
  /api/v1/publications:
    get:
      tags:
      - Publication Resource
      summary: Get all publications
      operationId: getPublications
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Publication'
    put:
      tags:
      - Publication Resource
      summary: Create publication
      operationId: updatePublication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Publication'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publication'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - openId:
        - curator
    post:
      tags:
      - Publication Resource
      summary: Create publication
      operationId: createPublication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Publication'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                format: int64
                type: integer
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - openId:
        - curator
  /api/v1/publications/{id}:
    get:
      tags:
      - Publication Resource
      summary: Get publication by ID
      operationId: getPublicationById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publication'
    delete:
      tags:
      - Publication Resource
      summary: Delete publication
      operationId: deletePublication
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "204":
          description: No Content
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - openId:
        - curator
  /api/v1/users/bearerToken:
    post:
      tags:
      - Users Resource
      summary: Get token for legacy API
      operationId: getLegacyApiToken
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccesTokenRepresentationRecord'
  /api/v1/users/forgotLegacyPassword:
    post:
      tags:
      - Users Resource
      summary: "The end user has forgotten the legacy password they used for VCell,\
        \ so they will be emailed it."
      operationId: forgotLegacyPassword
      parameters:
      - name: userID
        in: query
        schema:
          type: string
      responses:
        "200":
          description: Legacy password sent in email
        "401":
          description: Need to login to Auth0
        "500":
          description: Internal Error
  /api/v1/users/mapUser:
    post:
      tags:
      - Users Resource
      summary: map vcell user
      operationId: mapUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginInfoForMapping'
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: boolean
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - openId:
        - user
  /api/v1/users/mappedUser:
    get:
      tags:
      - Users Resource
      summary: Get mapped VCell identity
      operationId: getMappedUser
      responses:
        "200":
          description: "Successful, returning the identity"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserIdentityJSONSafe'
        "404":
          description: Identity not found
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - openId:
        - user
  /api/v1/users/me:
    get:
      tags:
      - Users Resource
      summary: Get current user
      operationId: getMe
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'
  /api/v1/users/newUser:
    post:
      tags:
      - Users Resource
      summary: create vcell user
      operationId: mapNewUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationInfo'
      responses:
        "200":
          description: "Successful, returning the identity"
        "409":
          description: "VCell Identity not mapped, userid already exists"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - openId:
        - user
  /api/v1/users/unmapUser/{userName}:
    put:
      tags:
      - Users Resource
      summary: remove vcell identity mapping
      operationId: unmapUser
      parameters:
      - name: userName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - openId:
        - user
components:
  schemas:
    AccesTokenRepresentationRecord:
      type: object
      properties:
        token:
          type: string
        creationDateSeconds:
          format: int64
          type: integer
        expireDateSeconds:
          format: int64
          type: integer
        userId:
          type: string
        userKey:
          type: string
    Application:
      type: object
    BioModel:
      type: object
      properties:
        bmKey:
          type: string
        name:
          type: string
        privacy:
          format: int32
          type: integer
        groupUsers:
          type: array
          items:
            type: string
        savedDate:
          format: int64
          type: integer
        annot:
          type: string
        branchID:
          type: string
        physModelKey:
          type: string
        ownerName:
          type: string
        ownerKey:
          type: string
        simulations:
          type: array
          items:
            $ref: '#/components/schemas/Simulation'
        applications:
          type: array
          items:
            $ref: '#/components/schemas/Application'
    BiomodelRef:
      type: object
      properties:
        bmKey:
          format: int64
          type: integer
        name:
          type: string
        ownerName:
          type: string
        ownerKey:
          format: int64
          type: integer
        versionFlag:
          format: int32
          type: integer
    Date:
      format: date
      type: string
      example: 2022-03-10
    HelloWorldMessage:
      type: object
      properties:
        message:
          type: string
    Identity:
      type: object
      properties:
        principal_name:
          type: string
        roles:
          type: array
          items:
            type: string
        attributes:
          type: array
          items:
            type: string
        credentials:
          type: array
          items:
            type: string
    MathmodelRef:
      type: object
      properties:
        mmKey:
          format: int64
          type: integer
        name:
          type: string
        ownerName:
          type: string
        ownerKey:
          format: int64
          type: integer
        versionFlag:
          format: int32
          type: integer
    Publication:
      type: object
      properties:
        pubKey:
          format: int64
          type: integer
        title:
          type: string
        authors:
          type: array
          items:
            type: string
        year:
          format: int32
          type: integer
        citation:
          type: string
        pubmedid:
          type: string
        doi:
          type: string
        endnoteid:
          format: int32
          type: integer
        url:
          type: string
        wittid:
          format: int32
          type: integer
        biomodelRefs:
          type: array
          items:
            $ref: '#/components/schemas/BiomodelRef'
        mathmodelRefs:
          type: array
          items:
            $ref: '#/components/schemas/MathmodelRef'
        date:
          $ref: '#/components/schemas/Date'
    Simulation:
      type: object
      properties:
        name:
          type: string
    UserIdentityJSONSafe:
      type: object
      properties:
        userName:
          type: string
        id:
          type: number
        subject:
          type: string
        insertDate:
          type: string
    UserLoginInfoForMapping:
      type: object
      properties:
        userID:
          type: string
        password:
          type: string
    UserRegistrationInfo:
      type: object
      properties:
        userID:
          type: string
        title:
          type: string
        organization:
          type: string
        country:
          type: string
        emailNotification:
          type: boolean
  securitySchemes:
    openId:
      type: openIdConnect
      description: Authentication
      openIdConnectUrl: https://dev-dzhx7i2db3x3kkvq.us.auth0.com/.well-known/openid-configuration
