# Build stage
FROM node:20.11-alpine3.19 AS build

RUN apk update && apk add git

RUN mkdir -p /app

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build_island

# -----------------

FROM nginx:1.17.1-alpine
COPY --from=build /app/dist/login-demo /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
