#!/usr/bin/env bash

DIR=${0%/*}
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
cd $DIR

if [ "$#" -ne 1 ] ; then
   echo "========= MOCK SLURM scancel =========="
   echo "usage scancel jobnumber"
   exit 1;
fi

jobid=$1

if [ ! -e "$DIR/slurm-$jobid.pid" ]; then
   echo "process id file not found"
   exit 1;
fi

pid=$(cat $DIR/slurm-$jobid.pid)

kill -9 $pid
if [[ $? -ne 0 ]]; then
   echo "job $jobid does not exist"
   exit 1
else
   echo "killed job $jobid"
   exit 0
fi
