name: CI-cloud-containers

on:
  workflow_dispatch:
#    inputs:
#      tag_name:
#        description: 'version tag'
#        required: true
#        default: 7.4.0.23

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the VCell version from tags
      id: version
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: set global environment variables
      run: |
        echo "VCELL_TAG=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        echo "VCELL_REPO_NAMESPACE=ghcr.io/jcschaff" >> $GITHUB_ENV
    - name: setup java 8 with maven cache
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: 'maven'
    - name: Install Singularity # to make singularity image for cluster
      uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3
    - name: build and publish all images
      shell: bash
      # ./build.sh all ${{ env.VCELL_REPO_NAMESPACE }} ${{ env.VCELL_TAG }}
      # ./build.sh api ${{ env.VCELL_REPO_NAMESPACE }} ${{ env.VCELL_TAG }}
      run: |
        cd docker/build-cloud
        sudo docker login -u ${{ secrets.ACTION_USER }} -p ${{ secrets.ACTION_TOKEN }} ghcr.io
        docker login -u ${{ secrets.ACTION_USER }} -p ${{ secrets.ACTION_TOKEN }} ghcr.io
        ./build.sh all ${{ env.VCELL_REPO_NAMESPACE }} ${{ env.VCELL_TAG }}
        cd singularity-vm
        singularity remote login -u ${{ secrets.ACTION_USER }} -p ${{ secrets.ACTION_TOKEN }} oras://ghcr.io
    - name: tag as latest and push to registry
      shell: bash
      run: |
        for CONTAINER in vcell-api vcell-batch vcell-clientgen vcell-data vcell-db vcell-mongo vcell-sched vcell-submit vcell-web;\
        do docker tag ${VCELL_REPO_NAMESPACE}/$CONTAINER:${VCELL_TAG} ${VCELL_REPO_NAMESPACE}/$CONTAINER:latest;\
        docker tag ${VCELL_REPO_NAMESPACE}/$CONTAINER:${VCELL_TAG} ${VCELL_REPO_NAMESPACE}/$CONTAINER:${{ steps.version.outputs.tag }};\
        docker push --all-tags ${VCELL_REPO_NAMESPACE}/$CONTAINER;\
        done
        cd docker/build/singularity-vm
        singularity push -U $(ls *img) oras://${VCELL_REPO_NAMESPACE}/vcell-batch-singularity:${VCELL_TAG}
        singularity push -U $(ls *img) oras://${VCELL_REPO_NAMESPACE}/vcell-batch-singularity:${{ steps.version.outputs.tag }}
        singularity push -U $(ls *img) oras://${VCELL_REPO_NAMESPACE}/vcell-batch-singularity:latest
        
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
