name: CI-cloud-containers

on:
  workflow_dispatch:
#    inputs:
#      tag_name:
#        description: 'version tag'
#        required: true
#        default: 7.4.0.23

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the VCell version from tags
      id: version
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: set global environment variables
      run: |
        echo "VCELL_TAG=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        echo "VCELL_REPO_NAMESPACE=ghcr.io/modeltwice-llc" >> $GITHUB_ENV
    - name: setup java 8 with maven cache
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: 'maven'
    - name: Install Singularity # to make singularity image for cluster
      uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3
    - name: Add Linux dependencies
      shell: bash
      run: |
        mvn -version
        java -version
        mvn --batch-mode clean install dependency:copy-dependencies
    - name: build and publish all images
      shell: bash
      # ./build.sh all ${{ env.VCELL_REPO_NAMESPACE }} ${{ env.VCELL_TAG }}
      # ./build.sh api ${{ env.VCELL_REPO_NAMESPACE }} ${{ env.VCELL_TAG }}
      run: |
        cd docker/build-cloud
        sudo docker login -u ${{ secrets.ACTION_USER }} -p ${{ secrets.ACTION_TOKEN }} ghcr.io
        docker login -u ${{ secrets.ACTION_USER }} -p ${{ secrets.ACTION_TOKEN }} ghcr.io
        ./build.sh --skip-maven api ${{ env.VCELL_REPO_NAMESPACE }} ${{ env.VCELL_TAG }}
    - name: tag as latest and push to registry
      shell: bash
#        for CONTAINER in vcell-api vcell-batch vcell-clientgen vcell-data vcell-db vcell-mongo vcell-sched vcell-submit vcell-web;\
      run: |
        for CONTAINER in vcell-api;\
        do docker tag ${VCELL_REPO_NAMESPACE}/$CONTAINER:${VCELL_TAG} ${VCELL_REPO_NAMESPACE}/$CONTAINER:latest;\
        docker push --all-tags ${VCELL_REPO_NAMESPACE}/$CONTAINER;\
        done

#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3
#      if: ${{ failure() }}
